// =============================================================
// ゲーム登録所（レジストリ）
// =============================================================
// 新しいゲームはこの配列に1エントリ追記するだけで追加できる。
// 手順は docs/ADDING_A_GAME.md を参照。
//
// ルール:
//   - 追記専用（並べ替え・削除はしない）
//   - id と no は一度リリースしたら変更しない（保存データのキー）
//   - 公開をやめるときは削除せず status: 'retired' にする
// =============================================================
import type { GameMeta } from '../game-api/types';

// ゲームアイコン（端末非依存の自作SVG。絵文字は iOS/Android/iPad で見た目が変わるため、
// 意匠が重要なものは SVG で固定する。ID 由来のグラデ背景の代わりに svg 内で背景も描く）
const ICON_REVERSI =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#2a9d54'/><circle cx='35' cy='50' r='20' fill='#1b1b1b'/><circle cx='65' cy='50' r='20' fill='#fbfbfb' stroke='#c8c8d0' stroke-width='1.5'/></svg>";
const ICON_GOMOKU =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#c8953c'/><circle cx='35' cy='50' r='20' fill='#1b1b1b'/><circle cx='65' cy='50' r='20' fill='#fbfbfb' stroke='#b98a37' stroke-width='1.5'/></svg>";
const ICON_POKER =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#f6f7fb'/><rect x='6' y='6' width='88' height='88' rx='18' fill='none' stroke='#dcdfe8' stroke-width='2'/><g font-family='sans-serif' font-size='34' text-anchor='middle'><text x='32' y='44' fill='#1a1a1a'>♠︎</text><text x='68' y='44' fill='#d3213a'>♥︎</text><text x='32' y='82' fill='#d3213a'>♦︎</text><text x='68' y='82' fill='#1a1a1a'>♣︎</text></g></svg>";

export const games: GameMeta[] = [
  // === ここに新しいゲームを追記 ===
  {
    id: 'reversi',
    no: 1,
    title: 'リバーシ',
    kana: 'りばーし',
    description: 'CPUと対戦！ばんをはさんで自分の色をふやすボードゲーム。先攻・後攻とつよさがえらべる。',
    category: 'puzzle',
    orientation: 'any',
    scoring: 'points',
    medals: { bronze: 33, silver: 44, gold: 55 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ばんをはさんで自分の色をふやそう。おわりに石が多いほうがかち！',
      controls: ['あきマスをタップ：石をおく', 'おけるところは・でひかる', '「まった」でひとつ前にもどる'],
      tips: ['かどは取られない強い場所', 'とちゅうの数より、終わりに多いほうが大事'],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUにはじめて勝った' },
      { id: 'beat-hard', name: 'つよいをたおした', desc: 'つよいCPUに勝った' },
      { id: 'shutout', name: 'かんぷう', desc: '相手を0まいにして勝った' },
      { id: 'four-corners', name: 'すみせいあつ', desc: '四すみをぜんぶ取って勝った', secret: true },
      { id: 'comeback', name: '大ぎゃくてん', desc: 'おわりぎわの劣勢から逆転で勝った', secret: true },
    ],
    icon: { emoji: '⚫', svg: ICON_REVERSI },
    addedIn: '0.5.0',
    load: () => import('./reversi/game'),
  },
  {
    id: 'block-break',
    no: 2,
    title: 'ブロックくずし',
    kana: 'ぶろっくくずし',
    description: 'バーでボールをはねかえしてブロックをこわそう。アイテムでパワーアップ！',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 800, silver: 1800, gold: 3200 },
    timeToPlay: 'mid',
    help: {
      goal: 'バーでボールをはねかえして、ブロックをぜんぶこわそう！ボールを下におとすとライフがへるよ。',
      controls: [
        'ゆびで左右になぞる：バーがうごく',
        '端末をかたむけてもうごく（つかわなくてもOK）',
        'おちてくる四角いアイテムをバーでとる：パワーアップ！',
        'タップ：ボールをはっしゃ',
      ],
      tips: [
        'バーのはしに当てると、ななめにとばせるよ',
        '★のブロックはかならずアイテムをおとす',
        'ボールがふえたら、ぜんぶは追わなくてだいじょうぶ',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてクリア', desc: 'ステージ1をクリアした' },
      { id: 'no-miss', name: 'ノーミス', desc: 'ボールを1こもおとさずにステージをクリアした' },
      { id: 'triple', name: 'トリプルボール', desc: 'ボールを3こ同時にとばした' },
      { id: 'all-clear', name: 'ぜんめんクリア', desc: 'ステージ5までぜんぶクリアした' },
      { id: 'combo-10', name: 'コンボめいじん', desc: 'バーにふれずに10れんぞくでブロックをこわした', secret: true },
      { id: 'item-8', name: 'あつめめいじん', desc: '1プレイでアイテムを8こキャッチした', secret: true },
    ],
    icon: { emoji: '🧱' },
    addedIn: '0.5.0',
    load: () => import('./block-break/game'),
  },
  {
    id: 'speed',
    no: 3,
    title: 'スピード',
    kana: 'すぴーど',
    description: 'CPUとリアルタイム対戦のトランプスピード。ローカルルールもえらべる！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 120, silver: 230, gold: 300 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'まん中の2つの台に、数字がとなり（1ちがい）のカードをどんどん重ねよう。先に手もちのカードがなくなったほうのかち！',
      controls: [
        'ひかっているカードをタップ：台に出す',
        '両方の台に出せるときは、いいほうへ自動でとぶよ',
        'おたがい出せないときは「せーの！」で自動的に1まいめくる',
      ],
      tips: [
        'KとAはつながっているよ（ループ）',
        'CPUのカードも見える。つぎの手を先よみしよう',
        'ローカルルール（同じ数字・ジョーカーなど）は開始前にえらべる',
      ],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUにはじめて勝った' },
      { id: 'beat-hard', name: 'つよいをたおした', desc: 'つよいCPUに勝った' },
      { id: 'speed-45', name: 'スピードスター', desc: '45びょう以内に勝った' },
      { id: 'combo-5', name: 'れんぞくだし', desc: 'CPUより先に5まいれんぞくで出した' },
      { id: 'no-seno', name: 'ノンストップ', desc: '「せーの」なしで勝った', secret: true },
      { id: 'joker-fin', name: 'ジョーカーじまい', desc: 'さいごの1まいがジョーカーだった', secret: true },
    ],
    icon: { emoji: '🃏' },
    addedIn: '0.5.0',
    load: () => import('./speed/game'),
  },
  {
    id: 'maze',
    no: 4,
    title: 'かたむきメイロ',
    kana: 'かたむきめいろ',
    description: 'スマホをかたむけてボールをころがし、ゴールをめざすランダム迷路。毎回ちがう迷路！',
    category: 'sensor',
    orientation: 'landscape',
    optionalSensors: ['motion'],
    scoring: 'timeMs',
    medals: { bronze: 60_000, silver: 40_000, gold: 25_000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'スタートからゴール🏁まで、ボールをはこぼう。はやくゴールするほど高評価！',
      controls: [
        'スマホをかたむける：ボールがころがる',
        '画面をドラッグ：かたむきの代わりに動かせる（センサーがなくてもOK）',
        '左上の「すいへい」：今の持ち方を水平にリセット',
      ],
      tips: ['かたむけすぎると壁にぶつかってスピードダウン。少しずつ！', 'まよったら「ヒント」ありで正解ルートが見えるよ'],
    },
    achievements: [
      { id: 'first-goal', name: 'はじめてゴール', desc: 'めいろをクリアした' },
      { id: 'speedy', name: 'すいすい', desc: '15びょう以内にクリアした' },
      { id: 'big-clear', name: 'だいめいろ突破', desc: '「おおきい」めいろをクリアした' },
      { id: 'tilt-master', name: 'かたむきマスター', desc: 'ドラッグを使わずにクリアした', secret: true },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: 'ちいさい・ふつう・おおきいをぜんぶクリアした', secret: true },
    ],
    icon: { emoji: '🌀' },
    addedIn: '0.5.0',
    load: () => import('./maze/game'),
  },
  {
    id: 'hit-and-blow',
    no: 5,
    title: 'えもじヒットアンドブロー',
    kana: 'えもじひっとあんどぶろー',
    description: 'かくれた絵文字のならびを推理してあてよう。ヒントは「ズバリ」と「おしい」の数だけ！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 120, silver: 240, gold: 360 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'かくれた絵文字のならび（あんごう）をあてよう。「こたえあわせ」でヒントが出るよ。',
      controls: [
        'パレットの絵文字をタップ：左のマスから置く',
        'おいたマスをタップ：けす（「やりなおし」で全部けす）',
        'そろったら「こたえあわせ」：⭕ズバリと🔶おしいの数が出る',
        '「メモ」ON中にパレットをタップ：ちがう絵文字に✕印（じぶん用メモ）',
      ],
      tips: [
        '⭕ズバリ＝絵も場所も合ってる。🔶おしい＝絵はあるけど場所ちがい',
        'どの絵が✕かをメモしながら、少しずつ場所をしぼろう',
        'まよったら設定で「ヒント」ありにすると1マスだけ教えてくれる',
      ],
    },
    achievements: [
      { id: 'first-solve', name: 'はじめてのすいり', desc: 'あんごうをはじめて当てた' },
      { id: 'sharp', name: 'するどいすいり', desc: '4かい以内で当てた' },
      { id: 'big-clear', name: 'だいすいり', desc: '「5もじ」で当てた' },
      { id: 'dup-clear', name: 'かぶりマスター', desc: '「かぶりあり」で当てた', secret: true },
      { id: 'no-hint', name: 'じぶんの力で', desc: 'ヒントなしで当てた' },
      { id: 'speedy', name: 'はやときめいじん', desc: '60びょう以内に当てた', secret: true },
    ],
    icon: { emoji: '🎯' },
    addedIn: '0.5.0',
    load: () => import('./hit-and-blow/game'),
  },
  {
    id: 'treasure-dig',
    no: 6,
    title: 'ほりほりたからじま',
    kana: 'ほりほりたからじま',
    description: 'すなをほって、かくれた たからをあつめる すいりパズル。ばくだんは 数字のヒントとアイテムで かわそう！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 180, silver: 320, gold: 480 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'すなをほって、ばくだん💣いがいのマスをぜんぶひらこう。数字は「まわり8マスにある ばくだんの数」だよ。',
      controls: [
        '⭐のマスからほると あんぜん',
        'マスをタップ：ほる（🚩モードのときは旗を立てる）',
        'ひらいた数字をタップ：旗の数がそろっていたら、まわりを一気にほる',
        '🔍レーダー：えらんだ3×3の ばくだんに旗を立てる',
        '⛏️ビッグシャベル：えらんだ3×3の あんぜんなマスを一気にほる',
      ],
      tips: [
        '🛡️おまもりを持っていると、ばくだんを1回だけふせげる',
        '💎たからをほると得点アップ。まけても持ち帰れるよ',
        '数字のまわりの「かくれマスの数」が数字と同じなら、そこはぜんぶばくだん！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめての島', desc: 'はじめて島をぜんぶほった' },
      { id: 'no-shield', name: 'ノーダメージ', desc: 'おまもりを使わずにクリアした' },
      { id: 'big-clear', name: 'おおきな島のぬし', desc: '「おおきい」島をクリアした' },
      { id: 'all-sizes', name: 'しまめぐり', desc: 'ちいさい・ふつう・おおきい、ぜんぶの島をクリアした', secret: true },
      { id: 'speedy', name: 'いそいでほった', desc: '60びょう以内にクリアした', secret: true },
      { id: 'no-flag', name: 'はたいらず', desc: '🚩もレーダーも使わずにクリアした', secret: true },
    ],
    icon: { emoji: '🏝️' },
    addedIn: '0.20.0',
    load: () => import('./treasure-dig/game'),
  },
  {
    id: 'number-place',
    no: 7,
    title: 'ナンプレ',
    kana: 'なんぷれ',
    description: 'たて・よこ・ブロックに1つずつ。定番の数字パズル。4×4から9×9まで、メモやヒントつきで あそびやすい！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 450, gold: 650 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'たて・よこ・ふとわく（ブロック）のどれにも、同じ数字が1つずつ入るように、ぜんぶのマスをうめよう。',
      controls: [
        'マスをタップ → 下の数字をタップで書きこむ',
        '同じ数字をもういちどおすと消える（⌫けす でもOK）',
        '✏️メモ：候補の数字を小さく書いておける',
        '💡ヒント：えらんだマスに正しい数字を入れる（3回まで）',
        'とちゅうでやめても「つづきから」であそべる',
      ],
      tips: [
        '同じ数字が光るハイライトを手がかりにしよう',
        'のこり1マスの行・列・ブロックからうめるとかんたん',
        'まちがい表示は設定でOFFにもできる（ノーミスにちょうせん！）',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのかんせい', desc: 'はじめてパズルを完成させた' },
      { id: 'clear-9', name: 'ほんかくクリア', desc: '9×9のパズルを完成させた' },
      { id: 'no-mistake', name: 'ノーミス', desc: 'まちがい0回で完成させた' },
      { id: 'no-hint', name: 'じぶんの力で', desc: 'ヒントを使わずに完成させた' },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: '4×4・6×6・9×9をぜんぶ完成させた', secret: true },
      { id: 'speedy', name: 'はやわざ', desc: '9×9を12分以内に完成させた', secret: true },
    ],
    icon: { emoji: '🔢' },
    addedIn: '0.20.0',
    load: () => import('./number-place/game'),
  },
  {
    id: 'calc-rush',
    no: 8,
    title: 'けいさんラッシュ',
    kana: 'けいさんらっしゅ',
    description: 'つぎつぎ出てくる けいさんを 60びょうで なんもん とける？れんぞく正解の コンボで 点数アップ！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 400, gold: 600 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '60びょうのあいだに、けいさんの答えを えらんで どんどん正解しよう！れんぞくで正解すると コンボボーナス！',
      controls: [
        '答えを 4つのボタンから えらんでタップ',
        'まちがえると コンボが0に。もんだいは そのままだから おちついて えらびなおそう',
        'むずかしさは 4しゅるい（たしざん・たしひき・九九・ミックス）',
      ],
      tips: [
        'れんぞく正解の コンボで 1問の点数が どんどん上がる（さいだい+10）',
        'むずかしい もんだいほど 1問の点数が 高いよ',
        'さいごまで まちがい0なら ノーミスボーナス +50！',
      ],
    },
    achievements: [
      { id: 'debut-10', name: 'けいさんデビュー', desc: '1プレイで10問 正解した' },
      { id: 'combo-10', name: 'コンボめいじん', desc: '10れんぞくで正解した' },
      { id: 'count-30', name: 'けいさんマシン', desc: '1プレイで30問 正解した' },
      { id: 'no-miss', name: 'パーフェクト', desc: 'まちがい0で 15問いじょう正解した' },
      { id: 'all-modes', name: 'ぜんモードせいは', desc: 'ぜんぶのむずかしさで 10問いじょう正解した', secret: true },
      { id: 'combo-20', name: 'コンボでんせつ', desc: '20れんぞくで正解した', secret: true },
    ],
    icon: { emoji: '🧮' },
    addedIn: '0.20.0',
    load: () => import('./calc-rush/game'),
  },
  {
    id: 'fruit-catch',
    no: 9,
    title: 'フルーツキャッチ',
    kana: 'ふるーつきゃっち',
    description: 'スマホをかたむけて カゴを動かし、落ちてくる フルーツをキャッチ！ばくだんは よけてね。',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 600, silver: 1500, gold: 3000 },
    timeToPlay: 'short',
    help: {
      goal: '落ちてくる フルーツを カゴでキャッチして 点数をあつめよう！💣ばくだんを 取るとライフがへるよ。',
      controls: [
        'スマホを 左右にかたむける：カゴが動く',
        '画面を 左右にドラッグしてもOK（センサーがなくてもあそべる）',
        '🍎フルーツ＝得点／⭐ゴールデン＝大得点＋ライフ回復／💣ばくだん＝ライフ−1',
      ],
      tips: [
        'フルーツを 取るほど コンボで 点数の ばいりつUP（さいだい×5）',
        'コンボは💣ばくだんを 取ると 0にもどる。取りこぼしは へいきだよ',
        'だんだん はやくなるよ。ばくだんは 思いきって よけよう',
      ],
    },
    achievements: [
      { id: 'first-catch', name: 'はじめてのしゅうかく', desc: 'フルーツをはじめてキャッチした' },
      { id: 'combo-15', name: 'コンボめいじん', desc: '15こ れんぞくでキャッチした' },
      { id: 'golden', name: 'きんのフルーツ', desc: '⭐ゴールデンをキャッチした' },
      { id: 'fifty', name: 'おおもり', desc: '1プレイで50こ キャッチした' },
      { id: 'no-bomb', name: 'ばくだんゼロ', desc: 'ばくだんを1こも取らずに1000点いじょう', secret: true },
      { id: 'survivor', name: 'ねばりのカゴ', desc: 'レベル5まで ねばった', secret: true },
    ],
    icon: { emoji: '🧺' },
    addedIn: '0.20.0',
    load: () => import('./fruit-catch/game'),
  },
  {
    id: 'shake-dash',
    no: 10,
    title: 'シャカシャカ・ダッシュ',
    kana: 'しゃかしゃかだっしゅ',
    description: 'スマホを ふって走る 50mそうきょうそう！ライバルより 先にゴールしよう。タイムが みじかいほど すごい。',
    category: 'reflex',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'timeMs',
    medals: { bronze: 15_000, silver: 12_000, gold: 9_500 },
    timeToPlay: 'short',
    help: {
      goal: 'スマホを ふって（またはタップ連打で）はやく走り、50m先の ゴールをめざそう！タイムを きそうよ。',
      controls: [
        'スマホを ふる：ふるほど 速く走る',
        'タップ連打でもOK（センサーがなくても あそべる）',
        '⚡ダッシュゾーンを 通ると さらに加速！',
      ],
      tips: [
        '🥇きんのライバルに 勝てたら 金メダルきゅうの タイム！',
        'とちゅうで 手を止めると スピードが おちる。ゴールまで ふりつづけよう',
        'ダッシュゾーンでこそ 全力でふろう',
      ],
    },
    achievements: [
      { id: 'first-goal', name: 'はつゴール', desc: '50mを 完走した' },
      { id: 'beat-silver', name: 'ぎんごえ', desc: '🥈ぎんのライバルより 先にゴールした' },
      { id: 'beat-gold', name: 'きんごえ', desc: '🥇きんのライバルより 先にゴールした' },
      { id: 'speedy', name: 'でんこうせっか', desc: '10びょう以内で ゴールした', secret: true },
      { id: 'no-stop', name: 'ノンストップ', desc: '一度も スピードを おとさずゴールした', secret: true },
      { id: 'big-lead', name: 'だんとつ', desc: '🥇きんに 大きな差をつけて 勝った', secret: true },
    ],
    icon: { emoji: '🏃' },
    addedIn: '0.20.0',
    load: () => import('./shake-dash/game'),
  },
  {
    id: 'gomoku',
    no: 11,
    title: '五目ならべ',
    kana: 'ごもくならべ',
    description: 'CPUと対戦！たて・よこ・ななめに 石を5つ 先にならべたら かち。先手・後手と つよさがえらべる。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 150, silver: 320, gold: 520 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'たて・よこ・ななめ どれかに 自分の石を5つ 先にならべよう！先手（⚫）から こうたいで おくよ。',
      controls: ['あいているマスをタップ：石をおく', '「まった」：じぶんの手を1つ（あいての手も）もどす'],
      tips: ['4つ ならんだら 両はしを ふさがれる前に のばそう', 'あいてが 3つ・4つ ならべてきたら 早めに とめよう', 'ふたつの ねらいを 同時に作ると 止められない！'],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUに はじめて勝った' },
      { id: 'beat-strong', name: 'つよいをたおした', desc: 'つよいCPUに 勝った' },
      { id: 'quick', name: 'そっこう', desc: '8手いない で勝った', secret: true },
      { id: 'no-undo', name: 'じつりょく', desc: 'まったを 使わずに 勝った' },
      { id: 'gote-win', name: 'あとのせしょうり', desc: '後手（⚪）で 勝った', secret: true },
      { id: 'diagonal', name: 'ななめめいじん', desc: 'ななめの5ならびで 勝った', secret: true },
    ],
    icon: { emoji: '🔵', svg: ICON_GOMOKU },
    addedIn: '0.20.0',
    load: () => import('./gomoku/game'),
  },
  {
    id: 'poker',
    no: 12,
    title: 'ポーカー',
    kana: 'ぽーかー',
    description: 'トランプのドローポーカー。5まい配られ、のこす札をえらんで引き直し、いい役をつくろう！5ラウンド合計で勝負。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 150, silver: 280, gold: 450 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '5まいの手札から いい「役」をつくって 点数をあつめよう！5ラウンドの 合計スコアで しょうぶ。',
      controls: [
        'のこしたい カードをタップ：「キープ」になる',
        '「ひく」：キープしていない札を すてて 引き直す',
        '役が できたら 得点。「つぎへ」で 次のラウンド',
      ],
      tips: [
        'ワンペアが あれば のこして、あとを 引き直すと 役が のびやすい',
        '同じマーク4まいは あと1まいで フラッシュ！',
        '役の強さ：ワンペア<ツーペア<スリーカード<ストレート<フラッシュ<フルハウス<フォーカード',
      ],
    },
    achievements: [
      { id: 'first-role', name: 'はつやく', desc: 'はじめて役（ワンペア以上）をつくった' },
      { id: 'flush-made', name: 'フラッシュ！', desc: 'フラッシュをつくった' },
      { id: 'full-made', name: 'フルハウス！', desc: 'フルハウスをつくった' },
      { id: 'four-made', name: 'フォーカード！', desc: 'フォーカードをつくった', secret: true },
      { id: 'super', name: 'スーパーやく', desc: 'ストレートフラッシュ以上をつくった', secret: true },
      { id: 'high-total', name: 'ポーカーめいじん', desc: '合計250点いじょう', secret: true },
    ],
    icon: { emoji: '🎴', svg: ICON_POKER },
    addedIn: '0.20.0',
    load: () => import('./poker/game'),
  },
  {
    id: 'slide-puzzle',
    no: 13,
    title: 'スライドパズル',
    kana: 'すらいどぱずる',
    description: '1マスあけて 数字タイルをスライド！バラバラの ばんめんを 1からじゅんばんに ならべよう。3×3〜5×5。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 400, gold: 650 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'バラバラの タイルを スライドさせて、1から さいごまで じゅんばんに ならべよう！',
      controls: ['空いているマスの となりの タイルをタップ：そこへ スライド', '「まぜなおす」：もういちど バラバラにする'],
      tips: ['まず 上のだんから そろえると やりやすい', 'そろったタイルは 色がかわる', 'あわてず 空きマスの うごきを 考えよう'],
    },
    achievements: [
      { id: 'first-solve', name: 'はつクリア', desc: 'はじめて そろえた' },
      { id: 'clear-normal', name: '15パズル制覇', desc: '4×4を クリアした' },
      { id: 'clear-hard', name: '24パズル制覇', desc: '5×5を クリアした', secret: true },
      { id: 'speedy', name: 'はやとき', desc: '4×4を 90びょう以内で クリアした', secret: true },
      { id: 'sharp', name: 'むだのないうごき', desc: '4×4を 70手以内で クリアした', secret: true },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: '3×3・4×4・5×5を ぜんぶ クリアした', secret: true },
    ],
    icon: { emoji: '🧩' },
    addedIn: '0.20.0',
    load: () => import('./slide-puzzle/game'),
  },
  {
    id: 'piano-memory',
    no: 14,
    title: 'おぼえてピアノ',
    kana: 'おぼえてぴあの',
    description: '光って鳴る けんばん（ドレミファソラシド）の じゅんばんを おぼえて、同じ通りに たたこう！よこ向きの きおくゲーム。',
    category: 'memory',
    orientation: 'landscape',
    scoring: 'points',
    medals: { bronze: 80, silver: 180, gold: 320 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'お手本で 光って鳴った けんばんを おぼえて、同じ順に タップしよう！正解すると 1つずつ 長くなるよ。',
      controls: [
        'お手本を よく見て・よく きく（👀）',
        '「きみのばん！」で 同じ順に けんばんをタップ（🎹）',
        '「もう1回きく」で お手本を もう一度（2回まで）',
      ],
      tips: [
        'けんばんの 「いろ」と「音」と「ばしょ」を いっしょに おぼえよう',
        '声に出して ドレミを 歌うと おぼえやすい',
        '1つ でも まちがえると おわり。あわてず いこう',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのメロディ', desc: 'はじめて お手本を 正解した' },
      { id: 'len-5', name: '5つ おぼえた', desc: '5音の れつを 正解した' },
      { id: 'len-8', name: '8つ おぼえた', desc: '8音の れつを 正解した' },
      { id: 'len-12', name: 'きおくの達人', desc: '12音の れつを 正解した', secret: true },
      { id: 'speed-clear', name: 'はやわざ', desc: '「はやい」テンポで 5音まで 覚えた', secret: true },
      { id: 'no-replay', name: 'じぶんの記憶で', desc: '「もう1回きく」を使わずに 5音まで 覚えた', secret: true },
    ],
    icon: { emoji: '🎹' },
    addedIn: '0.20.0',
    load: () => import('./piano-memory/game'),
  },
  {
    id: 'star-drop',
    no: 15,
    title: 'スタードロップ',
    kana: 'すたーどろっぷ',
    description: '落ちてくるブロックを 横1列そろえて消そう！⭐スターでボーナス、💣ボムで ドカンとお助け。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 500, silver: 1500, gold: 3500 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ブロックを 横1れつ すきまなく そろえると 消えて 得点！積み上がって 天井についたら おしまい。',
      controls: [
        '◀ ▶：よこに動かす（長押しで つづけて動く）',
        '⟳：まわす　⬇：はやく落とす　⤓：一気に ストン',
        '⭐を含む れつを消すと ボーナス／💣は着地で まわり3×3を ドカン',
      ],
      tips: [
        'いちどに 2〜4れつ 消すと 大量点（4れつ＝特大！）',
        'こまったら 💣ボムで 山をくずせる',
        'つぎのブロックを 見て おく場所を 考えよう',
      ],
    },
    achievements: [
      { id: 'first-line', name: 'はつライン', desc: 'はじめて 1れつ消した' },
      { id: 'four-line', name: 'よんれつ消し', desc: '1どに 4れつ 消した' },
      { id: 'star-5', name: 'スターあつめ', desc: '1プレイで ⭐を5こ 消した' },
      { id: 'bomb-boom', name: 'ドッカン', desc: '💣ボムを 爆発させた' },
      { id: 'level-5', name: 'スピードアップ', desc: 'レベル5に 到達した', secret: true },
      { id: 'score-hi', name: 'ブロックめいじん', desc: '2000点いじょう とった', secret: true },
    ],
    icon: { emoji: '⭐' },
    addedIn: '0.20.0',
    load: () => import('./star-drop/game'),
  },
  {
    id: 'just-stop',
    no: 16,
    title: 'ぴったりストップ',
    kana: 'ぴったりすとっぷ',
    description: '左右に動くライトを、みどりの「ここ！」ゾーンでタップして止めよう。まん中に近いほど高得点！',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 600, silver: 1100, gold: 1600 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '左右に動くライトを、ねらいのゾーンでタップして止めよう。まん中の金色「ぴったり」に近いほど高得点！ぜんぶで10回。',
      controls: [
        '「ストップ！」ボタン（またはバー）をタップ：ライトを止める',
        'みどり＝ナイス／金色＝ぴったり（さいこう！）',
        'ミスしても だいじょうぶ。すぐ次のラウンドへ',
      ],
      tips: [
        'れんぞくで「ナイス」いじょうを出すと コンボボーナス（さいだい+50）',
        'むずかしいほど ライトが速く・ゾーンが せまくなるけど 点数の ばいりつUP',
        'あわてず、ゾーンに来る すこし手前で ねらおう',
      ],
    },
    achievements: [
      { id: 'first-pittari', name: 'はつぴったり', desc: 'はじめて「ぴったり」を出した' },
      { id: 'combo-5', name: 'れんぱつ', desc: '5かい れんぞくで 成功した（ナイス以上）' },
      { id: 'pittari-5', name: 'ぴったりマスター', desc: '1プレイで「ぴったり」を5回 出した' },
      { id: 'perfect', name: 'かんぺき！', desc: '10ラウンド ぜんぶ「ぴったり」', secret: true },
      { id: 'hard-clear', name: 'うでだめし', desc: '「むずかしい」を さいごまで あそんだ' },
      { id: 'score-hi', name: 'たかとくてん', desc: '1200点いじょう とった', secret: true },
    ],
    icon: { emoji: '⏱️' },
    addedIn: '0.20.0',
    load: () => import('./just-stop/game'),
  },
  {
    id: 'fishing',
    no: 17,
    title: 'のんびりさかなつり',
    kana: 'のんびりさかなつり',
    description: 'ウキが しずんだ しゅんかんに あわせて 魚を つり上げよう。かわ・いけ・うみで 魚図鑑を あつめる まったりゲーム。',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 500, silver: 1000, gold: 1800 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ウキが「！」としずんだ しゅんかんに「あわせる」でタップして 魚をつろう！ぜんぶで8かい。つれた魚は ずかんに あつまるよ。',
      controls: [
        '「つる 🎣」：糸を なげる',
        'ウキが しずんで「！」が出たら すぐ「あわせる！」',
        '早すぎ（すっぽ抜け）・おそすぎ（バラシ）は つれないよ',
      ],
      tips: [
        'つりば（かわ・いけ・うみ）で つれる魚が ちがう',
        'ジャストのタイミングで あわせると ボーナス点！',
        'たまに ヌシや たからばこも…？ ずかんを コンプリートしよう',
      ],
    },
    achievements: [
      { id: 'first-catch', name: 'はつづり', desc: 'はじめて 魚をつった' },
      { id: 'big-fish', name: 'おおものGET', desc: 'おおきな魚を つった' },
      { id: 'rare-fish', name: 'レアなさかな', desc: 'レアな魚を つった', secret: true },
      { id: 'many-fish', name: 'たくさんつり', desc: '1プレイで 6ひきいじょう つった' },
      { id: 'zukan-complete', name: 'ずかんコンプ', desc: 'さかなずかんを ぜんぶ うめた', secret: true },
      { id: 'just-hook', name: 'ジャストフッキング', desc: 'ジャストのタイミングで つった', secret: true },
    ],
    icon: { emoji: '🎣' },
    addedIn: '0.20.0',
    load: () => import('./fishing/game'),
  },
  {
    id: 'number-merge',
    no: 18,
    title: 'すうじがったい',
    kana: 'すうじがったい',
    description: 'スワイプで 同じ数字を くっつけて 倍・倍に！大きな数を めざす 定番パズル。4×4と5×5。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 3000, silver: 8000, gold: 18000 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'スワイプで タイルを 動かして、同じ数字どうしを くっつけよう（2+2=4, 4+4=8…）。大きな数を つくって 高得点！',
      controls: [
        'スワイプ（上下左右）：ぜんぶのタイルが その方向へ動く',
        '画面下の 矢印ボタンでもOK',
        'とちゅうで やめても「つづきから」で さいかいできる',
      ],
      tips: [
        '大きい数は かどに よせると じゃまになりにくい',
        '1手で たくさん くっつけると 気もちいい＆高得点',
        '動かせなく なったら おしまい。よく考えて！',
      ],
    },
    achievements: [
      { id: 'first-merge', name: 'はつがったい', desc: 'はじめて タイルを くっつけた' },
      { id: 'reach-256', name: '256たっせい', desc: '256のタイルを つくった' },
      { id: 'reach-1024', name: '1024たっせい', desc: '1024のタイルを つくった' },
      { id: 'reach-2048', name: '2048たっせい！', desc: '2048のタイルを つくった', secret: true },
      { id: 'multi-merge', name: 'いちどにたくさん', desc: '1手で 3組いじょう まとめて くっつけた', secret: true },
      { id: 'score-hi', name: 'たかとくてん', desc: '10000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🔟' },
    addedIn: '0.20.0',
    load: () => import('./number-merge/game'),
  },
  {
    id: 'road-race',
    no: 19,
    title: 'よけよけレース',
    kana: 'よけよけれーす',
    description: '前から来る車やコーンを よけながら 走る レースゲーム。⭐で得点、🚀でブースト！どこまで いけるかな？',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 1500, silver: 3500, gold: 7000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '前から来る 車🚗や コーン🚧を よけて、できるだけ 遠くまで 走ろう！⭐は得点、🚀はブースト。3回ぶつかると おしまい。',
      controls: [
        '画面の 左半分／右半分を おす：車が その方向へうごく（おしっぱなしで つづく）',
        'スマホを かたむけてもOK（センサーがなくてもあそべる）',
        '⭐あつめて得点／🚀でブースト（すこしのあいだ 無敵で加速）',
      ],
      tips: [
        'スピードは だんだん 上がる。早めに よけよう',
        'たくさんの車と すれちがうほど 得点アップ',
        'ぶつかった直後は しばらく 無敵（点滅中）',
      ],
    },
    achievements: [
      { id: 'first-drive', name: 'はつドライブ', desc: '1000mを 走った' },
      { id: 'no-crash', name: 'ノークラッシュ', desc: '1回もぶつからずに 2000m 走った' },
      { id: 'overtake-20', name: 'すれちがいめいじん', desc: '1プレイで 20台の車と すれちがった' },
      { id: 'star-10', name: 'スターあつめ', desc: '1プレイで ⭐を10個 あつめた' },
      { id: 'far-3000', name: 'かっとび', desc: '3000mまで 走った', secret: true },
      { id: 'score-hi', name: 'レースの達人', desc: '6000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🏎️' },
    addedIn: '0.20.0',
    load: () => import('./road-race/game'),
  },
  {
    id: 'space-shooter',
    no: 20,
    title: 'うちゅうシューティング',
    kana: 'うちゅうしゅーてぃんぐ',
    description: '自動で弾を撃つ 縦シューティング。せまってくる 敵をたおし、パワーアップやボスに ちょうせん！',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 1500, silver: 4000, gold: 8000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '自機は じどうで 弾を撃つよ。左右に動いて せまってくる 敵👾を たおそう！敵に ぶつかる・下まで通されると ライフがへる。ライフ3。',
      controls: [
        '画面の 左半分／右半分を おす：自機が うごく（おしっぱなしで つづく）',
        'スマホを かたむけてもOK（センサーがなくてもあそべる）',
        '弾は じどう。💊で3wayショット／🛡️でシールド',
      ],
      tips: [
        'ねらった敵の 真下に 入ると あてやすい',
        '敵弾は 動いて よけよう',
        '5ウェーブごとに ボス🛸。HPバーを ゼロに！',
      ],
    },
    achievements: [
      { id: 'first-kill', name: 'げきついデビュー', desc: '1プレイで 敵を10体 たおした' },
      { id: 'wave-5', name: 'ウェーブ5', desc: '5ウェーブ目に とうたつした' },
      { id: 'no-hit-wave', name: 'ノーダメウェーブ', desc: '1ウェーブを 被弾ゼロで クリアした' },
      { id: 'powerup', name: 'パワーアップ', desc: 'パワーアップを 取った' },
      { id: 'boss-down', name: 'ボスげきは', desc: 'ボスを たおした', secret: true },
      { id: 'score-hi', name: 'エースパイロット', desc: '3000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🚀' },
    addedIn: '0.20.0',
    load: () => import('./space-shooter/game'),
  },
];

// 検証用ゲーム（開発ビルド限定。本番ビルドには一切含まれない）
if (import.meta.env.DEV) {
  const dev = await import('./dev/index');
  games.push(...dev.devGames);
}

/** 公開中のゲーム（retired を除き、番号順） */
export function activeGames(): GameMeta[] {
  return games.filter((g) => g.status !== 'retired').sort((a, b) => a.no - b.no);
}

export function gameById(id: string): GameMeta | undefined {
  return games.find((g) => g.id === id);
}
