// =============================================================
// ゲーム登録所（レジストリ）
// =============================================================
// 新しいゲームはこの配列に1エントリ追記するだけで追加できる。
// 手順は docs/ADDING_A_GAME.md を参照。
//
// ルール:
//   - 追記専用（並べ替え・削除はしない）
//   - id と no は一度リリースしたら変更しない（保存データのキー）
//   - 公開をやめるときは削除せず status: 'retired' にする
// =============================================================
import type { GameMeta } from '../game-api/types';

// ゲームアイコン（端末非依存の自作SVG。絵文字は iOS/Android/iPad で見た目が変わるため、
// 意匠が重要なものは SVG で固定する。ID 由来のグラデ背景の代わりに svg 内で背景も描く）
const ICON_REVERSI =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#2a9d54'/><circle cx='35' cy='50' r='20' fill='#1b1b1b'/><circle cx='65' cy='50' r='20' fill='#fbfbfb' stroke='#c8c8d0' stroke-width='1.5'/></svg>";
const ICON_GOMOKU =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#c8953c'/><circle cx='35' cy='50' r='20' fill='#1b1b1b'/><circle cx='65' cy='50' r='20' fill='#fbfbfb' stroke='#b98a37' stroke-width='1.5'/></svg>";
const ICON_POKER =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#f6f7fb'/><rect x='6' y='6' width='88' height='88' rx='18' fill='none' stroke='#dcdfe8' stroke-width='2'/><g font-family='sans-serif' font-size='34' text-anchor='middle'><text x='32' y='44' fill='#1a1a1a'>♠︎</text><text x='68' y='44' fill='#d3213a'>♥︎</text><text x='32' y='82' fill='#d3213a'>♦︎</text><text x='68' y='82' fill='#1a1a1a'>♣︎</text></g></svg>";
const ICON_TICTACTOE =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#5b6cf0'/><g stroke='#ffffff' stroke-width='4' stroke-linecap='round' opacity='.85'><line x1='40' y1='20' x2='40' y2='80'/><line x1='60' y1='20' x2='60' y2='80'/><line x1='20' y1='40' x2='80' y2='40'/><line x1='20' y1='60' x2='80' y2='60'/></g><circle cx='30' cy='30' r='7' fill='none' stroke='#ffd54a' stroke-width='4.5'/><g stroke='#ff6b6b' stroke-width='4.5' stroke-linecap='round'><line x1='64' y1='64' x2='76' y2='76'/><line x1='76' y1='64' x2='64' y2='76'/></g></svg>";
const ICON_NINJA =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#1b2340'/><circle cx='79' cy='21' r='9' fill='#f2ecca'/><circle cx='83' cy='18' r='7' fill='#1b2340'/><circle cx='50' cy='54' r='27' fill='#2a3355'/><rect x='23' y='44' width='54' height='17' rx='8.5' fill='#e8ecf6'/><circle cx='40' cy='52' r='4.5' fill='#1b2340'/><circle cx='60' cy='52' r='4.5' fill='#1b2340'/><rect x='40' y='79' width='20' height='5' rx='2.5' fill='#d3455e'/></svg>";
const ICON_SOLITAIRE =
  "<svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'><rect width='100' height='100' rx='24' fill='#0e6b3d'/><g stroke='#c3ccdd' stroke-width='1.5'><rect x='20' y='30' width='34' height='46' rx='5' fill='#fff' transform='rotate(-12 37 53)'/><rect x='34' y='26' width='34' height='46' rx='5' fill='#fff'/></g><text x='40' y='52' font-family='sans-serif' font-size='22' font-weight='bold' fill='#d3213a' text-anchor='middle'>A</text><text x='40' y='68' font-family='sans-serif' font-size='16' fill='#d3213a' text-anchor='middle'>♥</text></svg>";

export const games: GameMeta[] = [
  // === ここに新しいゲームを追記 ===
  {
    id: 'reversi',
    no: 1,
    title: 'リバーシ',
    kana: 'りばーし',
    description: 'CPUと対戦！ばんをはさんで自分の色をふやすボードゲーム。先攻・後攻とつよさがえらべる。',
    category: 'puzzle',
    orientation: 'any',
    scoring: 'points',
    medals: { bronze: 33, silver: 44, gold: 55 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ばんをはさんで自分の色をふやそう。おわりに石が多いほうがかち！',
      controls: ['あきマスをタップ：石をおく', 'おけるところは・でひかる', '「まった」でひとつ前にもどる'],
      tips: ['かどは取られない強い場所', 'とちゅうの数より、終わりに多いほうが大事'],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUにはじめて勝った' },
      { id: 'beat-hard', name: 'つよいをたおした', desc: 'つよいCPUに勝った' },
      { id: 'shutout', name: 'かんぷう', desc: '相手を0まいにして勝った' },
      { id: 'four-corners', name: 'すみせいあつ', desc: '四すみをぜんぶ取って勝った', secret: true },
      { id: 'comeback', name: '大ぎゃくてん', desc: 'おわりぎわの劣勢から逆転で勝った', secret: true },
    ],
    icon: { emoji: '⚫', svg: ICON_REVERSI },
    addedIn: '0.5.0',
    load: () => import('./reversi/game'),
  },
  {
    id: 'block-break',
    no: 2,
    title: 'ブロックくずし',
    kana: 'ぶろっくくずし',
    description: 'バーでボールをはねかえしてブロックをこわそう。アイテムでパワーアップ！',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 800, silver: 1800, gold: 3200 },
    timeToPlay: 'mid',
    help: {
      goal: 'バーでボールをはねかえして、ブロックをぜんぶこわそう！ボールを下におとすとライフがへるよ。',
      controls: [
        'ゆびで左右になぞる：バーがうごく',
        '端末をかたむけてもうごく（つかわなくてもOK）',
        'おちてくる四角いアイテムをバーでとる：パワーアップ！',
        'タップ：ボールをはっしゃ',
      ],
      tips: [
        'バーのはしに当てると、ななめにとばせるよ',
        '★のブロックはかならずアイテムをおとす',
        'ボールがふえたら、ぜんぶは追わなくてだいじょうぶ',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてクリア', desc: 'ステージ1をクリアした' },
      { id: 'no-miss', name: 'ノーミス', desc: 'ボールを1こもおとさずにステージをクリアした' },
      { id: 'triple', name: 'トリプルボール', desc: 'ボールを3こ同時にとばした' },
      { id: 'all-clear', name: 'ぜんめんクリア', desc: 'ステージ5までぜんぶクリアした' },
      { id: 'combo-10', name: 'コンボめいじん', desc: 'バーにふれずに10れんぞくでブロックをこわした', secret: true },
      { id: 'item-8', name: 'あつめめいじん', desc: '1プレイでアイテムを8こキャッチした', secret: true },
    ],
    icon: { emoji: '🧱' },
    addedIn: '0.5.0',
    load: () => import('./block-break/game'),
  },
  {
    id: 'speed',
    no: 3,
    title: 'スピード',
    kana: 'すぴーど',
    description: 'CPUとリアルタイム対戦のトランプスピード。ローカルルールもえらべる！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 120, silver: 230, gold: 300 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'まん中の2つの台に、数字がとなり（1ちがい）のカードをどんどん重ねよう。先に手もちのカードがなくなったほうのかち！',
      controls: [
        'ひかっているカードをタップ：台に出す',
        '両方の台に出せるときは、いいほうへ自動でとぶよ',
        'おたがい出せないときは「せーの！」で自動的に1まいめくる',
      ],
      tips: [
        'KとAはつながっているよ（ループ）',
        'CPUのカードも見える。つぎの手を先よみしよう',
        'ローカルルール（同じ数字・ジョーカーなど）は開始前にえらべる',
      ],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUにはじめて勝った' },
      { id: 'beat-hard', name: 'つよいをたおした', desc: 'つよいCPUに勝った' },
      { id: 'speed-45', name: 'スピードスター', desc: '45びょう以内に勝った' },
      { id: 'combo-5', name: 'れんぞくだし', desc: 'CPUより先に5まいれんぞくで出した' },
      { id: 'no-seno', name: 'ノンストップ', desc: '「せーの」なしで勝った', secret: true },
      { id: 'joker-fin', name: 'ジョーカーじまい', desc: 'さいごの1まいがジョーカーだった', secret: true },
    ],
    icon: { emoji: '🃏' },
    addedIn: '0.5.0',
    load: () => import('./speed/game'),
  },
  {
    id: 'maze',
    no: 4,
    title: 'かたむきメイロ',
    kana: 'かたむきめいろ',
    description: 'スマホをかたむけてボールをころがし、ゴールをめざすランダム迷路。毎回ちがう迷路！',
    category: 'sensor',
    orientation: 'landscape',
    optionalSensors: ['motion'],
    scoring: 'timeMs',
    medals: { bronze: 60_000, silver: 40_000, gold: 25_000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'スタートからゴール🏁まで、ボールをはこぼう。はやくゴールするほど高評価！',
      controls: [
        'スマホをかたむける：ボールがころがる',
        '画面をドラッグ：かたむきの代わりに動かせる（センサーがなくてもOK）',
        '左上の「すいへい」：今の持ち方を水平にリセット',
      ],
      tips: ['かたむけすぎると壁にぶつかってスピードダウン。少しずつ！', 'まよったら「ヒント」ありで正解ルートが見えるよ'],
    },
    achievements: [
      { id: 'first-goal', name: 'はじめてゴール', desc: 'めいろをクリアした' },
      { id: 'speedy', name: 'すいすい', desc: '15びょう以内にクリアした' },
      { id: 'big-clear', name: 'だいめいろ突破', desc: '「おおきい」めいろをクリアした' },
      { id: 'tilt-master', name: 'かたむきマスター', desc: 'ドラッグを使わずにクリアした', secret: true },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: 'ちいさい・ふつう・おおきいをぜんぶクリアした', secret: true },
    ],
    icon: { emoji: '🌀' },
    addedIn: '0.5.0',
    load: () => import('./maze/game'),
  },
  {
    id: 'hit-and-blow',
    no: 5,
    title: 'えもじヒットアンドブロー',
    kana: 'えもじひっとあんどぶろー',
    description: 'かくれた絵文字のならびを推理してあてよう。ヒントは「ズバリ」と「おしい」の数だけ！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 120, silver: 240, gold: 360 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'かくれた絵文字のならび（あんごう）をあてよう。「こたえあわせ」でヒントが出るよ。',
      controls: [
        'パレットの絵文字をタップ：左のマスから置く',
        'おいたマスをタップ：けす（「やりなおし」で全部けす）',
        'そろったら「こたえあわせ」：⭕ズバリと🔶おしいの数が出る',
        '「メモ」ON中にパレットをタップ：ちがう絵文字に✕印（じぶん用メモ）',
      ],
      tips: [
        '⭕ズバリ＝絵も場所も合ってる。🔶おしい＝絵はあるけど場所ちがい',
        'どの絵が✕かをメモしながら、少しずつ場所をしぼろう',
        'まよったら設定で「ヒント」ありにすると1マスだけ教えてくれる',
      ],
    },
    achievements: [
      { id: 'first-solve', name: 'はじめてのすいり', desc: 'あんごうをはじめて当てた' },
      { id: 'sharp', name: 'するどいすいり', desc: '4かい以内で当てた' },
      { id: 'big-clear', name: 'だいすいり', desc: '「5もじ」で当てた' },
      { id: 'dup-clear', name: 'かぶりマスター', desc: '「かぶりあり」で当てた', secret: true },
      { id: 'no-hint', name: 'じぶんの力で', desc: 'ヒントなしで当てた' },
      { id: 'speedy', name: 'はやときめいじん', desc: '60びょう以内に当てた', secret: true },
    ],
    icon: { emoji: '🎯' },
    addedIn: '0.5.0',
    load: () => import('./hit-and-blow/game'),
  },
  {
    id: 'treasure-dig',
    no: 6,
    title: 'ほりほりたからじま',
    kana: 'ほりほりたからじま',
    description: 'すなをほって、かくれた たからをあつめる すいりパズル。ばくだんは 数字のヒントとアイテムで かわそう！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 180, silver: 320, gold: 480 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'すなをほって、ばくだん💣いがいのマスをぜんぶひらこう。数字は「まわり8マスにある ばくだんの数」だよ。',
      controls: [
        '⭐のマスからほると あんぜん',
        'マスをタップ：ほる（🚩モードのときは旗を立てる）',
        'ひらいた数字をタップ：旗の数がそろっていたら、まわりを一気にほる',
        '🔍レーダー：えらんだ3×3の ばくだんに旗を立てる',
        '⛏️ビッグシャベル：えらんだ3×3の あんぜんなマスを一気にほる',
      ],
      tips: [
        '🛡️おまもりを持っていると、ばくだんを1回だけふせげる',
        '💎たからをほると得点アップ。まけても持ち帰れるよ',
        '数字のまわりの「かくれマスの数」が数字と同じなら、そこはぜんぶばくだん！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめての島', desc: 'はじめて島をぜんぶほった' },
      { id: 'no-shield', name: 'ノーダメージ', desc: 'おまもりを使わずにクリアした' },
      { id: 'big-clear', name: 'おおきな島のぬし', desc: '「おおきい」島をクリアした' },
      { id: 'all-sizes', name: 'しまめぐり', desc: 'ちいさい・ふつう・おおきい、ぜんぶの島をクリアした', secret: true },
      { id: 'speedy', name: 'いそいでほった', desc: '60びょう以内にクリアした', secret: true },
      { id: 'no-flag', name: 'はたいらず', desc: '🚩もレーダーも使わずにクリアした', secret: true },
    ],
    icon: { emoji: '🏝️' },
    addedIn: '0.20.0',
    load: () => import('./treasure-dig/game'),
  },
  {
    id: 'number-place',
    no: 7,
    title: 'ナンプレ',
    kana: 'なんぷれ',
    description: 'たて・よこ・ブロックに1つずつ。定番の数字パズル。4×4から9×9まで、メモやヒントつきで あそびやすい！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 450, gold: 650 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'たて・よこ・ふとわく（ブロック）のどれにも、同じ数字が1つずつ入るように、ぜんぶのマスをうめよう。',
      controls: [
        'マスをタップ → 下の数字をタップで書きこむ',
        '同じ数字をもういちどおすと消える（⌫けす でもOK）',
        '✏️メモ：候補の数字を小さく書いておける',
        '💡ヒント：えらんだマスに正しい数字を入れる（3回まで）',
        'とちゅうでやめても「つづきから」であそべる',
      ],
      tips: [
        '同じ数字が光るハイライトを手がかりにしよう',
        'のこり1マスの行・列・ブロックからうめるとかんたん',
        'まちがい表示は設定でOFFにもできる（ノーミスにちょうせん！）',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのかんせい', desc: 'はじめてパズルを完成させた' },
      { id: 'clear-9', name: 'ほんかくクリア', desc: '9×9のパズルを完成させた' },
      { id: 'no-mistake', name: 'ノーミス', desc: 'まちがい0回で完成させた' },
      { id: 'no-hint', name: 'じぶんの力で', desc: 'ヒントを使わずに完成させた' },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: '4×4・6×6・9×9をぜんぶ完成させた', secret: true },
      { id: 'speedy', name: 'はやわざ', desc: '9×9を12分以内に完成させた', secret: true },
    ],
    icon: { emoji: '🔢' },
    addedIn: '0.20.0',
    load: () => import('./number-place/game'),
  },
  {
    id: 'calc-rush',
    no: 8,
    title: 'けいさんラッシュ',
    kana: 'けいさんらっしゅ',
    description: 'つぎつぎ出てくる けいさんを 60びょうで なんもん とける？れんぞく正解の コンボで 点数アップ！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 400, gold: 600 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '60びょうのあいだに、けいさんの答えを えらんで どんどん正解しよう！れんぞくで正解すると コンボボーナス！',
      controls: [
        '答えを 4つのボタンから えらんでタップ',
        'まちがえると コンボが0に。もんだいは そのままだから おちついて えらびなおそう',
        'むずかしさは 4しゅるい（たしざん・たしひき・九九・ミックス）',
      ],
      tips: [
        'れんぞく正解の コンボで 1問の点数が どんどん上がる（さいだい+10）',
        'むずかしい もんだいほど 1問の点数が 高いよ',
        'さいごまで まちがい0なら ノーミスボーナス +50！',
      ],
    },
    achievements: [
      { id: 'debut-10', name: 'けいさんデビュー', desc: '1プレイで10問 正解した' },
      { id: 'combo-10', name: 'コンボめいじん', desc: '10れんぞくで正解した' },
      { id: 'count-30', name: 'けいさんマシン', desc: '1プレイで30問 正解した' },
      { id: 'no-miss', name: 'パーフェクト', desc: 'まちがい0で 15問いじょう正解した' },
      { id: 'all-modes', name: 'ぜんモードせいは', desc: 'ぜんぶのむずかしさで 10問いじょう正解した', secret: true },
      { id: 'combo-20', name: 'コンボでんせつ', desc: '20れんぞくで正解した', secret: true },
    ],
    icon: { emoji: '🧮' },
    addedIn: '0.20.0',
    load: () => import('./calc-rush/game'),
  },
  {
    id: 'fruit-catch',
    no: 9,
    title: 'フルーツキャッチ',
    kana: 'ふるーつきゃっち',
    description: 'スマホをかたむけて カゴを動かし、落ちてくる フルーツをキャッチ！ばくだんは よけてね。',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 600, silver: 1500, gold: 3000 },
    timeToPlay: 'short',
    help: {
      goal: '落ちてくる フルーツを カゴでキャッチして 点数をあつめよう！💣ばくだんを 取るとライフがへるよ。',
      controls: [
        'スマホを 左右にかたむける：カゴが動く',
        '画面を 左右にドラッグしてもOK（センサーがなくてもあそべる）',
        '🍎フルーツ＝得点／⭐ゴールデン＝大得点＋ライフ回復／💣ばくだん＝ライフ−1',
      ],
      tips: [
        'フルーツを れんぞくで 取るほど コンボで 点数の ばいりつUP（さいだい×5）',
        'フルーツを 取りこぼす（または💣を取る）と コンボは 0。3回つづけて 取りこぼすと ライフが へるよ',
        'だんだん はやく・ばくだんも ふえる。むりせず よけて、取れるフルーツを 確実に',
      ],
    },
    achievements: [
      { id: 'first-catch', name: 'はじめてのしゅうかく', desc: 'フルーツをはじめてキャッチした' },
      { id: 'combo-15', name: 'コンボめいじん', desc: '15こ れんぞくでキャッチした' },
      { id: 'golden', name: 'きんのフルーツ', desc: '⭐ゴールデンをキャッチした' },
      { id: 'fifty', name: 'おおもり', desc: '1プレイで50こ キャッチした' },
      { id: 'no-bomb', name: 'ばくだんゼロ', desc: 'ばくだんを1こも取らずに1000点いじょう', secret: true },
      { id: 'survivor', name: 'ねばりのカゴ', desc: 'レベル5まで ねばった', secret: true },
    ],
    icon: { emoji: '🧺' },
    addedIn: '0.20.0',
    load: () => import('./fruit-catch/game'),
  },
  {
    id: 'shake-dash',
    no: 10,
    title: 'シャカシャカ・ダッシュ',
    kana: 'しゃかしゃかだっしゅ',
    description: 'スマホを ふって走る 50mそうきょうそう！ライバルより 先にゴールしよう。タイムが みじかいほど すごい。',
    category: 'reflex',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'timeMs',
    medals: { bronze: 15_000, silver: 12_000, gold: 9_500 },
    timeToPlay: 'short',
    help: {
      goal: 'スマホを ふって（またはタップ連打で）はやく走り、50m先の ゴールをめざそう！タイムを きそうよ。',
      controls: [
        'スマホを ふる：ふるほど 速く走る',
        'タップ連打でもOK（センサーがなくても あそべる）',
        '⚡ダッシュゾーンを 通ると さらに加速！',
      ],
      tips: [
        '🥇きんのライバルに 勝てたら 金メダルきゅうの タイム！',
        'とちゅうで 手を止めると スピードが おちる。ゴールまで ふりつづけよう',
        'ダッシュゾーンでこそ 全力でふろう',
      ],
    },
    achievements: [
      { id: 'first-goal', name: 'はつゴール', desc: '50mを 完走した' },
      { id: 'beat-silver', name: 'ぎんごえ', desc: '🥈ぎんのライバルより 先にゴールした' },
      { id: 'beat-gold', name: 'きんごえ', desc: '🥇きんのライバルより 先にゴールした' },
      { id: 'speedy', name: 'でんこうせっか', desc: '10びょう以内で ゴールした', secret: true },
      { id: 'no-stop', name: 'ノンストップ', desc: '一度も スピードを おとさずゴールした', secret: true },
      { id: 'big-lead', name: 'だんとつ', desc: '🥇きんに 大きな差をつけて 勝った', secret: true },
    ],
    icon: { emoji: '🏃' },
    addedIn: '0.20.0',
    load: () => import('./shake-dash/game'),
  },
  {
    id: 'gomoku',
    no: 11,
    title: '五目ならべ',
    kana: 'ごもくならべ',
    description: 'CPUと対戦！たて・よこ・ななめに 石を5つ 先にならべたら かち。先手・後手と つよさがえらべる。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 150, silver: 320, gold: 520 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'たて・よこ・ななめ どれかに 自分の石を5つ 先にならべよう！先手（⚫）から こうたいで おくよ。',
      controls: ['あいているマスをタップ：石をおく', '「まった」：じぶんの手を1つ（あいての手も）もどす'],
      tips: ['4つ ならんだら 両はしを ふさがれる前に のばそう', 'あいてが 3つ・4つ ならべてきたら 早めに とめよう', 'ふたつの ねらいを 同時に作ると 止められない！'],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUに はじめて勝った' },
      { id: 'beat-strong', name: 'つよいをたおした', desc: 'つよいCPUに 勝った' },
      { id: 'quick', name: 'そっこう', desc: '8手いない で勝った', secret: true },
      { id: 'no-undo', name: 'じつりょく', desc: 'まったを 使わずに 勝った' },
      { id: 'gote-win', name: 'あとのせしょうり', desc: '後手（⚪）で 勝った', secret: true },
      { id: 'diagonal', name: 'ななめめいじん', desc: 'ななめの5ならびで 勝った', secret: true },
    ],
    icon: { emoji: '🔵', svg: ICON_GOMOKU },
    addedIn: '0.20.0',
    load: () => import('./gomoku/game'),
  },
  {
    id: 'poker',
    no: 12,
    title: 'ポーカー',
    kana: 'ぽーかー',
    description: 'トランプのドローポーカー。5まい配られ、のこす札をえらんで引き直し、いい役をつくろう！5ラウンド合計で勝負。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 150, silver: 280, gold: 450 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '5まいの手札から いい「役」をつくって 点数をあつめよう！5ラウンドの 合計スコアで しょうぶ。',
      controls: [
        'のこしたい カードをタップ：「キープ」になる',
        '「ひく」：キープしていない札を すてて 引き直す',
        '役が できたら 得点。「つぎへ」で 次のラウンド',
      ],
      tips: [
        'ワンペアが あれば のこして、あとを 引き直すと 役が のびやすい',
        '同じマーク4まいは あと1まいで フラッシュ！',
        '役の強さ：ワンペア<ツーペア<スリーカード<ストレート<フラッシュ<フルハウス<フォーカード',
      ],
    },
    achievements: [
      { id: 'first-role', name: 'はつやく', desc: 'はじめて役（ワンペア以上）をつくった' },
      { id: 'flush-made', name: 'フラッシュ！', desc: 'フラッシュをつくった' },
      { id: 'full-made', name: 'フルハウス！', desc: 'フルハウスをつくった' },
      { id: 'four-made', name: 'フォーカード！', desc: 'フォーカードをつくった', secret: true },
      { id: 'super', name: 'スーパーやく', desc: 'ストレートフラッシュ以上をつくった', secret: true },
      { id: 'high-total', name: 'ポーカーめいじん', desc: '合計250点いじょう', secret: true },
    ],
    icon: { emoji: '🎴', svg: ICON_POKER },
    addedIn: '0.20.0',
    load: () => import('./poker/game'),
  },
  {
    id: 'slide-puzzle',
    no: 13,
    title: 'スライドパズル',
    kana: 'すらいどぱずる',
    description: '1マスあけて 数字タイルをスライド！バラバラの ばんめんを 1からじゅんばんに ならべよう。3×3〜5×5。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 400, gold: 650 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'バラバラの タイルを スライドさせて、1から さいごまで じゅんばんに ならべよう！',
      controls: ['空いているマスの となりの タイルをタップ：そこへ スライド', '「まぜなおす」：もういちど バラバラにする'],
      tips: ['まず 上のだんから そろえると やりやすい', 'そろったタイルは 色がかわる', 'あわてず 空きマスの うごきを 考えよう'],
    },
    achievements: [
      { id: 'first-solve', name: 'はつクリア', desc: 'はじめて そろえた' },
      { id: 'clear-normal', name: '15パズル制覇', desc: '4×4を クリアした' },
      { id: 'clear-hard', name: '24パズル制覇', desc: '5×5を クリアした', secret: true },
      { id: 'speedy', name: 'はやとき', desc: '4×4を 90びょう以内で クリアした', secret: true },
      { id: 'sharp', name: 'むだのないうごき', desc: '4×4を 70手以内で クリアした', secret: true },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: '3×3・4×4・5×5を ぜんぶ クリアした', secret: true },
    ],
    icon: { emoji: '🧩' },
    addedIn: '0.20.0',
    load: () => import('./slide-puzzle/game'),
  },
  {
    id: 'piano-memory',
    no: 14,
    title: 'おぼえてピアノ',
    kana: 'おぼえてぴあの',
    description: '光って鳴る けんばん（ドレミファソラシド）の じゅんばんを おぼえて、同じ通りに たたこう！よこ向きの きおくゲーム。',
    category: 'memory',
    orientation: 'landscape',
    scoring: 'points',
    medals: { bronze: 80, silver: 180, gold: 320 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'お手本で 光って鳴った けんばんを おぼえて、同じ順に タップしよう！正解すると 1つずつ 長くなるよ。',
      controls: [
        'お手本を よく見て・よく きく（👀）',
        '「きみのばん！」で 同じ順に けんばんをタップ（🎹）',
        '「もう1回きく」で お手本を もう一度（2回まで）',
      ],
      tips: [
        'けんばんの 「いろ」と「音」と「ばしょ」を いっしょに おぼえよう',
        '声に出して ドレミを 歌うと おぼえやすい',
        '1つ でも まちがえると おわり。あわてず いこう',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのメロディ', desc: 'はじめて お手本を 正解した' },
      { id: 'len-5', name: '5つ おぼえた', desc: '5音の れつを 正解した' },
      { id: 'len-8', name: '8つ おぼえた', desc: '8音の れつを 正解した' },
      { id: 'len-12', name: 'きおくの達人', desc: '12音の れつを 正解した', secret: true },
      { id: 'speed-clear', name: 'はやわざ', desc: '「はやい」テンポで 5音まで 覚えた', secret: true },
      { id: 'no-replay', name: 'じぶんの記憶で', desc: '「もう1回きく」を使わずに 5音まで 覚えた', secret: true },
    ],
    icon: { emoji: '🎹' },
    addedIn: '0.20.0',
    load: () => import('./piano-memory/game'),
  },
  {
    id: 'star-drop',
    no: 15,
    title: 'スタードロップ',
    kana: 'すたーどろっぷ',
    description: '落ちてくるブロックを 横1列そろえて消そう！⭐スターでボーナス、💣ボムで ドカンとお助け。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 500, silver: 1500, gold: 3500 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ブロックを 横1れつ すきまなく そろえると 消えて 得点！積み上がって 天井についたら おしまい。',
      controls: [
        '◀ ▶：よこに動かす（長押しで つづけて動く）',
        '⟳：まわす　⬇：はやく落とす　⤓：一気に ストン',
        '⭐を含む れつを消すと ボーナス／💣は着地で まわり3×3を ドカン',
      ],
      tips: [
        'いちどに 2〜4れつ 消すと 大量点（4れつ＝特大！）',
        'こまったら 💣ボムで 山をくずせる',
        'つぎのブロックを 見て おく場所を 考えよう',
      ],
    },
    achievements: [
      { id: 'first-line', name: 'はつライン', desc: 'はじめて 1れつ消した' },
      { id: 'four-line', name: 'よんれつ消し', desc: '1どに 4れつ 消した' },
      { id: 'star-5', name: 'スターあつめ', desc: '1プレイで ⭐を5こ 消した' },
      { id: 'bomb-boom', name: 'ドッカン', desc: '💣ボムを 爆発させた' },
      { id: 'level-5', name: 'スピードアップ', desc: 'レベル5に 到達した', secret: true },
      { id: 'score-hi', name: 'ブロックめいじん', desc: '2000点いじょう とった', secret: true },
    ],
    icon: { emoji: '⭐' },
    addedIn: '0.20.0',
    load: () => import('./star-drop/game'),
  },
  {
    id: 'just-stop',
    no: 16,
    title: 'ぴったりストップ',
    kana: 'ぴったりすとっぷ',
    description: '左右に動くライトを、みどりの「ここ！」ゾーンでタップして止めよう。まん中に近いほど高得点！',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 600, silver: 1100, gold: 1600 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '左右に動くライトを、ねらいのゾーンでタップして止めよう。まん中の金色「ぴったり」に近いほど高得点！ぜんぶで10回。',
      controls: [
        '「ストップ！」ボタン（またはバー）をタップ：ライトを止める',
        'みどり＝ナイス／金色＝ぴったり（さいこう！）',
        'ミスしても だいじょうぶ。すぐ次のラウンドへ',
      ],
      tips: [
        'れんぞくで「ナイス」いじょうを出すと コンボボーナス（さいだい+50）',
        'むずかしいほど ライトが速く・ゾーンが せまくなるけど 点数の ばいりつUP',
        'あわてず、ゾーンに来る すこし手前で ねらおう',
      ],
    },
    achievements: [
      { id: 'first-pittari', name: 'はつぴったり', desc: 'はじめて「ぴったり」を出した' },
      { id: 'combo-5', name: 'れんぱつ', desc: '5かい れんぞくで 成功した（ナイス以上）' },
      { id: 'pittari-5', name: 'ぴったりマスター', desc: '1プレイで「ぴったり」を5回 出した' },
      { id: 'perfect', name: 'かんぺき！', desc: '10ラウンド ぜんぶ「ぴったり」', secret: true },
      { id: 'hard-clear', name: 'うでだめし', desc: '「むずかしい」を さいごまで あそんだ' },
      { id: 'score-hi', name: 'たかとくてん', desc: '1200点いじょう とった', secret: true },
    ],
    icon: { emoji: '⏱️' },
    addedIn: '0.20.0',
    load: () => import('./just-stop/game'),
  },
  {
    id: 'fishing',
    no: 17,
    title: 'のんびりさかなつり',
    kana: 'のんびりさかなつり',
    description: 'ウキが しずんだ しゅんかんに あわせて 魚を つり上げよう。かわ・いけ・うみで 魚図鑑を あつめる まったりゲーム。',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 500, silver: 1000, gold: 1800 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ウキが「！」としずんだ しゅんかんに「あわせる」でタップして 魚をつろう！ぜんぶで8かい。つれた魚は ずかんに あつまるよ。',
      controls: [
        '「つる 🎣」：糸を なげる',
        'ウキが しずんで「！」が出たら すぐ「あわせる！」',
        '早すぎ（すっぽ抜け）・おそすぎ（バラシ）は つれないよ',
      ],
      tips: [
        'ウキが ちょっとだけ しずむのは フェイント！ふかく しずんで「！」が出るまで がまん',
        'つりば（かわ・いけ・うみ）で つれる魚が ちがう。うみほど フェイントも 多いよ',
        'ジャストのタイミングで あわせると ボーナス点！大物ほど アタリは 一瞬',
        'たまに ヌシや たからばこも…？ ずかんを コンプリートしよう',
      ],
    },
    achievements: [
      { id: 'first-catch', name: 'はつづり', desc: 'はじめて 魚をつった' },
      { id: 'big-fish', name: 'おおものGET', desc: 'おおきな魚を つった' },
      { id: 'rare-fish', name: 'レアなさかな', desc: 'レアな魚を つった', secret: true },
      { id: 'many-fish', name: 'たくさんつり', desc: '1プレイで 6ひきいじょう つった' },
      { id: 'zukan-complete', name: 'ずかんコンプ', desc: 'さかなずかんを ぜんぶ うめた', secret: true },
      { id: 'just-hook', name: 'ジャストフッキング', desc: 'ジャストのタイミングで つった', secret: true },
    ],
    icon: { emoji: '🎣' },
    addedIn: '0.20.0',
    load: () => import('./fishing/game'),
  },
  {
    id: 'number-merge',
    no: 18,
    title: 'すうじがったい',
    kana: 'すうじがったい',
    description: 'スワイプで 同じ数字を くっつけて 倍・倍に！大きな数を めざす 定番パズル。4×4と5×5。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 3000, silver: 8000, gold: 18000 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'スワイプで タイルを 動かして、同じ数字どうしを くっつけよう（2+2=4, 4+4=8…）。大きな数を つくって 高得点！',
      controls: [
        'スワイプ（上下左右）：ぜんぶのタイルが その方向へ動く',
        '画面下の 矢印ボタンでもOK',
        'とちゅうで やめても「つづきから」で さいかいできる',
      ],
      tips: [
        '大きい数は かどに よせると じゃまになりにくい',
        '1手で たくさん くっつけると 気もちいい＆高得点',
        '動かせなく なったら おしまい。よく考えて！',
      ],
    },
    achievements: [
      { id: 'first-merge', name: 'はつがったい', desc: 'はじめて タイルを くっつけた' },
      { id: 'reach-256', name: '256たっせい', desc: '256のタイルを つくった' },
      { id: 'reach-1024', name: '1024たっせい', desc: '1024のタイルを つくった' },
      { id: 'reach-2048', name: '2048たっせい！', desc: '2048のタイルを つくった', secret: true },
      { id: 'multi-merge', name: 'いちどにたくさん', desc: '1手で 3組いじょう まとめて くっつけた', secret: true },
      { id: 'score-hi', name: 'たかとくてん', desc: '10000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🔟' },
    addedIn: '0.20.0',
    load: () => import('./number-merge/game'),
  },
  {
    id: 'road-race',
    no: 19,
    title: 'よけよけレース',
    kana: 'よけよけれーす',
    description: '前から来る車やコーンを よけながら 走る レースゲーム。⭐で得点、🚀でブースト！どこまで いけるかな？',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 1500, silver: 3500, gold: 7000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '前から来る 車🚗や コーン🚧を よけて、できるだけ 遠くまで 走ろう！⭐は得点、🚀はブースト。3回ぶつかると おしまい。',
      controls: [
        '画面の 左半分／右半分を おす：車が その方向へうごく（おしっぱなしで つづく）',
        'スマホを かたむけてもOK（センサーがなくてもあそべる）',
        '⭐あつめて得点／🚀でブースト（すこしのあいだ 無敵で加速）',
      ],
      tips: [
        'スピードは だんだん 上がる。早めに よけよう',
        'たくさんの車と すれちがうほど 得点アップ',
        'ぶつかった直後は しばらく 無敵（点滅中）',
      ],
    },
    achievements: [
      { id: 'first-drive', name: 'はつドライブ', desc: '1000mを 走った' },
      { id: 'no-crash', name: 'ノークラッシュ', desc: '1回もぶつからずに 2000m 走った' },
      { id: 'overtake-20', name: 'すれちがいめいじん', desc: '1プレイで 20台の車と すれちがった' },
      { id: 'star-10', name: 'スターあつめ', desc: '1プレイで ⭐を10個 あつめた' },
      { id: 'far-3000', name: 'かっとび', desc: '3000mまで 走った', secret: true },
      { id: 'score-hi', name: 'レースの達人', desc: '6000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🏎️' },
    addedIn: '0.20.0',
    load: () => import('./road-race/game'),
  },
  {
    id: 'space-shooter',
    no: 20,
    title: 'うちゅうシューティング',
    kana: 'うちゅうしゅーてぃんぐ',
    description: '自動で弾を撃つ 縦シューティング。せまってくる 敵をたおし、パワーアップやボスに ちょうせん！',
    category: 'action',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 1500, silver: 4000, gold: 8000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '自機は じどうで 弾を撃つよ。左右に動いて せまってくる 敵👾を たおそう！敵に ぶつかる・下まで通されると ライフがへる。ライフ3。',
      controls: [
        '画面の 左半分／右半分を おす：自機が うごく（おしっぱなしで つづく）',
        'スマホを かたむけてもOK（センサーがなくてもあそべる）',
        '弾は じどう。💊で3wayショット／🛡️でシールド',
      ],
      tips: [
        'ねらった敵の 真下に 入ると あてやすい',
        '敵弾は 動いて よけよう',
        '5ウェーブごとに ボス🛸。HPバーを ゼロに！',
      ],
    },
    achievements: [
      { id: 'first-kill', name: 'げきついデビュー', desc: '1プレイで 敵を10体 たおした' },
      { id: 'wave-5', name: 'ウェーブ5', desc: '5ウェーブ目に とうたつした' },
      { id: 'no-hit-wave', name: 'ノーダメウェーブ', desc: '1ウェーブを 被弾ゼロで クリアした' },
      { id: 'powerup', name: 'パワーアップ', desc: 'パワーアップを 取った' },
      { id: 'boss-down', name: 'ボスげきは', desc: 'ボスを たおした', secret: true },
      { id: 'score-hi', name: 'エースパイロット', desc: '3000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🚀' },
    addedIn: '0.20.0',
    load: () => import('./space-shooter/game'),
  },
  {
    id: 'pair-match',
    no: 21,
    title: 'ぺあさがし',
    kana: 'ぺあさがし',
    description: 'ふせたカードを2まいずつめくって、同じ絵のペアをぜんぶ見つけよう！定番のきおくゲーム。',
    category: 'memory',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 500, gold: 800 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'カードを2まいずつ めくって、同じ絵の ペアを ぜんぶ 見つけよう！めくる回数が少なく、はやいほど 高得点。',
      controls: [
        'カードをタップ：めくる（2まいまで）',
        '同じ絵なら そのままオープン、ちがったら 自動でもどる',
        'ばんの大きさは 開始前に えらべる（4×4 / 5×6 / 6×6）',
      ],
      tips: [
        'もどったカードの「場所と絵」を おぼえておこう',
        'れんぞくで ペアを当てると コンボ！',
        '大きいばんほど 高得点を ねらえるよ',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのペア', desc: 'はじめて ぜんぶ そろえた' },
      { id: 'combo-3', name: 'れんぞくヒット', desc: '3れんぞくで ペアを当てた' },
      { id: 'big-clear', name: 'おおきなばんクリア', desc: '6×6を そろえた' },
      { id: 'sharp', name: 'ものおぼえばつぐん', desc: 'めくった回数が とても少なく クリアした', secret: true },
      { id: 'speedy', name: 'はやおぼえ', desc: 'すばやく クリアした', secret: true },
      { id: 'all-sizes', name: 'ぜんサイズ制覇', desc: '4×4・5×6・6×6を ぜんぶ そろえた', secret: true },
    ],
    icon: { emoji: '🍒' },
    addedIn: '0.35.0',
    load: () => import('./pair-match/game'),
  },
  {
    id: 'mole-pop',
    no: 22,
    title: 'もぐらポンポン',
    kana: 'もぐらぽんぽん',
    description: '穴から出てくるもぐらをタップ！60びょうでなんびきたたける？金もぐらは大得点、ばくだんに注意！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 300, silver: 600, gold: 900 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '60びょうのあいだに、穴から出てくる🐹もぐらを どんどんタップ！れんぞくで たたくと コンボボーナス！',
      controls: [
        'もぐらをタップ：たたく（+10〜）',
        '✨金もぐら：大得点（+50〜）',
        '💣ばくだん：たたくと コンボが0に（点はへらないよ）',
      ],
      tips: [
        'にげられても コンボは つづくよ。あわてず ねらおう',
        'だんだん はやく・たくさん 出てくる',
        'コンボを つなぐと 1ぴきの点数が 上がる（さいだい+10）',
      ],
    },
    achievements: [
      { id: 'debut-10', name: 'もぐらデビュー', desc: '1プレイで 10ぴき たたいた' },
      { id: 'combo-10', name: 'コンボめいじん', desc: '10れんぞくで たたいた' },
      { id: 'golden', name: 'きんのもぐら', desc: '✨金もぐらを たたいた' },
      { id: 'count-30', name: 'もぐらハンター', desc: '1プレイで 30ぴき たたいた' },
      { id: 'no-bomb', name: 'ばくだんゼロ', desc: '💣を1回もたたかずに 25ひき たたいた', secret: true },
      { id: 'score-hi', name: 'たたきの達人', desc: '1000点いじょう とった', secret: true },
    ],
    icon: { emoji: '🐹' },
    addedIn: '0.35.0',
    load: () => import('./mole-pop/game'),
  },
  {
    id: 'stack-tower',
    no: 23,
    title: 'つみあげタワー',
    kana: 'つみあげたわー',
    description: '左右にうごくブロックをタイミングよく落として、どこまでも高く積み上げよう！ずれた分はカットされるよ。',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 400, silver: 800, gold: 1400 },
    timeToPlay: 'short',
    help: {
      goal: '左右にうごくブロックを タップで落として、どこまでも高く積もう！下の段から はみ出した分は カットされて どんどん細くなるよ。',
      controls: [
        '画面をタップ：ブロックを落とす',
        'ぴったり重なると カットなし＋ボーナス＋幅がすこし回復！',
        'ぜんぶ外れたら おしまい',
      ],
      tips: [
        '下の段の「はし」の点線に そろえるのが コツ',
        '高くなるほど スピードUP。おちついて！',
        'ぴったりを つづけると 幅をたもてる',
      ],
    },
    achievements: [
      { id: 'tower-10', name: '10だんたっせい', desc: '10だん つみあげた' },
      { id: 'pittari-3', name: 'ぴったりつづき', desc: '3れんぞくで ぴったり重ねた' },
      { id: 'tower-20', name: '20だんたっせい', desc: '20だん つみあげた' },
      { id: 'tower-30', name: 'そらのタワー', desc: '30だん つみあげた', secret: true },
      { id: 'no-cut-10', name: 'ノーカット10', desc: '一度もカットされずに 10だん つんだ', secret: true },
      { id: 'score-hi', name: 'タワーめいじん', desc: '1500点いじょう とった', secret: true },
    ],
    icon: { emoji: '🗼' },
    addedIn: '0.35.0',
    load: () => import('./stack-tower/game'),
  },
  {
    id: 'old-maid',
    no: 24,
    title: 'ババぬき',
    kana: 'ばばぬき',
    description: 'CPU2人との3人ババぬき。となりのカードを1まいずつ引いて、ペアをすてて、ジョーカーからにげきろう！',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    // スコアは順位の3値（1位150/2位70/3位10）しか出ないため、メダル＝銅:さんか/銀:2位/金:1位
    medals: { bronze: 10, silver: 70, gold: 150 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'となりの人のカードを1まいずつ引いて、同じ数字のペアをすてていこう。手札がなくなったら あがり！最後にジョーカーを持っていた人のまけ。',
      controls: [
        'じぶんの番：あいての伏せたカードを 1まいタップして引く',
        'ペアになったら 自動ですてるよ',
        'CPUが引くときは ドキドキしながら まとう',
      ],
      tips: [
        'ジョーカーを引いても あわてない。つぎに引かせちゃおう',
        'あいての残りまい数を 見ておこう',
        '1位あがりで 高得点！',
      ],
    },
    achievements: [
      { id: 'first-top', name: 'はつあがり', desc: 'はじめて 1位で あがった' },
      { id: 'pass-joker', name: 'ジョーカーばいばい', desc: 'ジョーカーを あいてに 引かせた' },
      { id: 'no-joker', name: 'にげきりチャンピオン', desc: '一度もジョーカーを持たずに 1位', secret: true },
      { id: 'top-3', name: 'ババぬきめいじん', desc: 'あわせて3回 1位に なった', secret: true },
      { id: 'quick-top', name: 'そっこうあがり', desc: 'じぶんの引き6回いないで 1位', secret: true },
      { id: 'comeback', name: 'だいぎゃくてん', desc: 'ジョーカーを持ったのに 1位', secret: true },
    ],
    icon: { emoji: '🤡' },
    addedIn: '0.35.0',
    load: () => import('./old-maid/game'),
  },
  {
    id: 'air-hockey',
    no: 25,
    title: 'エアホッケー',
    kana: 'えあほっけー',
    description: 'ゆびでマレットを動かして、パックをあいてのゴールへ！CPUと対戦、先に5点とったほうのかち。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // 最大スコア＝5点×30＋勝利50＋つよさ100＝300（5点先取で試合が終わるため）。金=つよいで5点勝ち
    medals: { bronze: 100, silver: 180, gold: 300 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '下のマレットを ゆびで動かして、パックを あいてのゴールに うちこもう！先に5点とるか、90びょうで 点が多いほうの かち。',
      controls: [
        '画面の下半分を ゆびでなぞる：マレットが ついてくる',
        'いきおいよく ぶつけると パックが はやく とぶ',
        'じぶんのゴール（下）を まもりながら せめよう',
      ],
      tips: [
        'ななめに あてると コースが かわる',
        'まっすぐ うちかえすだけじゃなく、かべの はねかえりも つかおう',
        'つよいCPUは まもりが かたい。すきを ねらえ！',
      ],
    },
    achievements: [
      { id: 'first-goal', name: 'はつシュート', desc: 'はじめて ゴールを きめた' },
      { id: 'first-win', name: 'はつしょうり', desc: 'CPUに はじめて勝った' },
      { id: 'beat-strong', name: 'つよいをたおした', desc: 'つよいCPUに 勝った' },
      { id: 'goal-10', name: 'ゴールコレクター', desc: 'あわせて 10ゴール きめた' },
      { id: 'shutout', name: 'かんぷうしょうり', desc: '1点もとられずに 勝った', secret: true },
      { id: 'speed-win', name: 'でんこうせっか', desc: '60びょう以内に 5点とって勝った', secret: true },
    ],
    icon: { emoji: '🏒' },
    addedIn: '0.35.0',
    load: () => import('./air-hockey/game'),
  },
  {
    id: 'color-word',
    no: 26,
    title: 'いろよみチャレンジ',
    kana: 'いろよみちゃれんじ',
    description: '「あお」と書いてあるのに 色は あか!? もじにだまされず、指示どおりに いろ／ことばをタップする 60びょうの頭こんがらがりバトル！',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 220, silver: 450, gold: 750 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '出てくる もじの【いろ】（または【ことば】）を、指示どおりに 下の4つから タップしよう！60びょうで なんもん 正解できるかな？',
      controls: [
        '上のバナーの指示を よく見る：【いろ】か【ことば】か',
        '【いろ】のとき：もじが 何色で 書かれているかを タップ',
        '【ことば】のとき：もじが 何と 書いてあるかを タップ',
      ],
      tips: [
        '「あお」と書いてあっても、いろが 赤なら…こたえは あか！（【いろ】のとき）',
        '「はんてん」では とちゅうで 指示が 切りかわる。バナーが 光ったら ちゅうい！',
        '「タイマー」は 1問 3びょうまで。むりせず おちついて',
      ],
    },
    achievements: [
      { id: 'debut-10', name: 'いろよみデビュー', desc: '1プレイで 10問 正解した' },
      { id: 'combo-10', name: 'コンボめいじん', desc: '10れんぞくで 正解した' },
      { id: 'no-miss', name: 'パーフェクト', desc: 'まちがい0で 15問いじょう 正解した' },
      { id: 'hard-15', name: 'タイマーの達人', desc: '「タイマー」で 15問 正解した' },
      { id: 'flip-master', name: 'きりかえめいじん', desc: '指示が切りかわった直後の問題に 10回 正解した', secret: true },
      { id: 'score-hi', name: 'いろよみチャンピオン', desc: '800点いじょう とった', secret: true },
    ],
    icon: { emoji: '🌈' },
    addedIn: '0.35.0',
    load: () => import('./color-word/game'),
  },
  {
    id: 'memory-maze',
    no: 27,
    title: 'きおくのめいろ',
    kana: 'きおくのめいろ',
    description: 'めいろを おぼえたら、かべが きりに 消える！きおくだけで ゴールをめざす ちょうせんパズル。ラウンドごとに めいろが 大きくなるよ。',
    category: 'memory',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 600, gold: 1000 },
    timeToPlay: 'mid',
    help: {
      goal: 'かべが 見えているあいだに みちを おぼえよう。きりで かべが 消えたら、きおくだけで 🐥を 🏁ゴールまで うごかす！見えないかべに ぶつかると ライフが へるよ（3回で おしまい）。',
      controls: [
        'スワイプ（上下左右）：1マス すすむ',
        '下の 矢印ボタンでもOK',
        'ぶつかった かべは 一瞬 見える。おぼえなおそう',
      ],
      tips: [
        'まがりかどの「かず」と「じゅんばん」を おぼえるのが コツ',
        'とおった みちには 色がつくよ。もどって べつの みちも ためせる',
        'ラウンドが すすむと めいろが 大きく・おぼえる時間が みじかくなる',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのきおく', desc: 'ラウンド1を クリアした' },
      { id: 'no-bump', name: 'ノーゴツン', desc: '1回も ぶつからずに ラウンドを クリアした' },
      { id: 'reach-7', name: 'ひろがるきおく', desc: '7×7の めいろに とうたつした' },
      { id: 'reach-9', name: 'きおくのたつじん', desc: '9×9の めいろに とうたつした' },
      { id: 'perfect-5', name: 'かんぺきなちず', desc: 'ラウンド5まで 1回も ぶつからなかった', secret: true },
      { id: 'score-hi', name: 'きおくチャンピオン', desc: '1200点いじょう とった', secret: true },
    ],
    icon: { emoji: '🌫️' },
    addedIn: '0.35.0',
    load: () => import('./memory-maze/game'),
  },
  {
    id: 'sheep-count',
    no: 28,
    title: 'ひつじかぞえ',
    kana: 'ひつじかぞえ',
    description: '夜のまきばで、さくを ぴょんと とびこえる 🐑ひつじだけを かぞえよう。🐐ヤギや🐺オオカミに まどわされないで！',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 150, silver: 300, gold: 480 },
    timeToPlay: 'mid',
    help: {
      goal: '柵をとびこえた 🐑ひつじの数を かぞえて、ウェーブのあとに こたえよう！🐐や🐺は かぞえちゃダメ。ぜんぶで3ラウンド。',
      controls: [
        'ウェーブ中は 見ているだけ。🐑を こっそり かぞえよう',
        'おわったら −・＋ で かずを あわせて「けってい」',
        'ぴったり正解で 大得点！おしい（±1）でも すこし もらえる',
      ],
      tips: [
        'こえに 出して かぞえると まちがえにくい',
        'ラウンドが すすむと はやく・かさなって とぶ',
        'まぎれものが 出ても あわてず 🐑だけ！',
      ],
    },
    achievements: [
      { id: 'first-exact', name: 'はじめてのぴったり', desc: 'ぴったり正解した' },
      { id: 'big-flock', name: 'おおきなむれ', desc: '12ひき以上の むれを ぴったり正解した' },
      { id: 'decoy-calm', name: 'まどわされない', desc: 'まぎれものが 4ひき以上いる ラウンドで ぴったり正解した' },
      { id: 'perfect-3', name: 'かんぺきなひつじかい', desc: '1プレイで 3ラウンド ぜんぶ ぴったり', secret: true },
      { id: 'exact-10', name: 'ひつじはかせ', desc: 'あわせて10回 ぴったり正解した', secret: true },
      { id: 'score-hi', name: 'かぞえチャンピオン', desc: '480点いじょう とった', secret: true },
    ],
    icon: { emoji: '🐑' },
    addedIn: '0.35.0',
    load: () => import('./sheep-count/game'),
  },
  {
    id: 'tilt-target',
    no: 29,
    title: 'かたむきまとあて',
    kana: 'かたむきまとあて',
    description: 'スマホをかたむけて ボールをころがし、光るまとの中で ピタッとキープ！60びょうで なんまい とれるかな？',
    category: 'sensor',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 400, silver: 800, gold: 1200 },
    timeToPlay: 'short',
    help: {
      goal: 'ボールを ころがして、光るまとの中に 入れよう。中に いつづけると リングがたまって 1まいゲット！60びょうで なんまい とれるか しょうぶ。',
      controls: [
        'スマホを かたむける：ボールが ころがる',
        '画面を ドラッグしてもOK（センサーがなくても あそべる）',
        'まとの中で じっと キープ！はやく とると ボーナス',
      ],
      tips: [
        'かたむけすぎると 通りすぎちゃう。少しずつ！',
        'とるたびに まとが ちいさくなるよ',
        'ボールを 止めたいときは 逆に かたむけて ブレーキ',
      ],
    },
    achievements: [
      { id: 'first-target', name: 'はつまとあて', desc: 'はじめて まとを とった' },
      { id: 'target-5', name: 'まとあてじょうず', desc: '1プレイで 5まい とった' },
      { id: 'target-10', name: 'まとあてめいじん', desc: '1プレイで 10まい とった' },
      { id: 'quick-3', name: 'すばやいボール', desc: '「はやどり」を 1プレイで 3回した', secret: true },
      { id: 'tilt-only', name: 'かたむきマスター', desc: 'ドラッグを使わずに 5まい とった', secret: true },
      { id: 'score-hi', name: 'まとあてチャンピオン', desc: '1100点いじょう とった', secret: true },
    ],
    icon: { emoji: '🎳' },
    addedIn: '0.35.0',
    load: () => import('./tilt-target/game'),
  },
  {
    id: 'rail-connect',
    no: 30,
    title: 'せんろつなぎ',
    kana: 'せんろつなぎ',
    description: 'バラバラの せんろタイルを くるくる回して、えきから ゴールまで つなげよう！つながると 汽車🚂が 走るよ。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 180, silver: 300, gold: 430 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'タイルをタップして せんろを 回し、🚉えきから 🏁ゴールまで 1本に つなげよう！つながると 汽車が 走って クリア。',
      controls: [
        'タイルをタップ：時計まわりに 90°回転',
        'まっすぐ と カーブ、2しゅるいの せんろが あるよ',
        'かんけいない タイルは 回さなくて OK',
      ],
      tips: [
        '🚉の となりから じゅんばんに つなぐと わかりやすい',
        '「めやす」の回転数いないで つなぐと ボーナス！',
        'はやく つなぐほど 点数アップ',
      ],
    },
    achievements: [
      { id: 'first-connect', name: 'はじめてのかいつう', desc: 'はじめて せんろを つないだ' },
      { id: 'clear-5', name: 'のびるせんろ', desc: '5×5を つないだ' },
      { id: 'clear-6', name: 'おおきなろせん', desc: '6×6を つないだ' },
      { id: 'par-clear', name: 'むだのないこうじ', desc: 'めやすの回転数いないで つないだ', secret: true },
      { id: 'speedy', name: 'いそぎのこうじ', desc: '60びょう以内に つないだ', secret: true },
      { id: 'all-sizes', name: 'せんろマスター', desc: '4×4・5×5・6×6を ぜんぶ つないだ', secret: true },
    ],
    icon: { emoji: '🚂' },
    addedIn: '0.35.0',
    load: () => import('./rail-connect/game'),
  },
  {
    id: 'double-rabbit',
    no: 31,
    title: 'ダブルうさぎ',
    kana: 'だぶるうさぎ',
    description: '左右の親指で 2ひきのうさぎを 同時にそうさ！🥕はキャッチ・🪨はよける。あたまが こんがらがる 2画面アクション。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 550, gold: 900 },
    timeToPlay: 'short',
    help: {
      goal: '左右のサイドに 1ぴきずつ いる🐰を 同時にあやつって、🥕にんじんを キャッチ！🪨いわは よけよう。にんじんの みのがしと いわの ゴツンで ライフがへるよ（3つで おしまい）。',
      controls: [
        '画面の 左はんぶんをタップ：左のうさぎが 列を きりかえ',
        '画面の 右はんぶんをタップ：右のうさぎが 列を きりかえ',
        '両手の おやゆびで 同時に そうさしよう！',
      ],
      tips: [
        '🥕は「とる」・🪨は「よける」。左右で ぎゃくの ことも あるから おちついて',
        'れんぞくキャッチの コンボで 点数アップ',
        'だんだん はやくなる。まずは 左右こうごに 見るクセを つけよう',
      ],
    },
    achievements: [
      { id: 'carrot-10', name: 'にんじんデビュー', desc: '1プレイで 🥕を10本 キャッチした' },
      { id: 'carrot-30', name: 'にんじんまみれ', desc: '1プレイで 🥕を30本 キャッチした' },
      { id: 'combo-15', name: 'ダブルコンボ', desc: '15れんぞくで キャッチした' },
      { id: 'no-rock', name: 'いわしらず', desc: '🪨に1回も当たらずに 🥕を15本 キャッチした' },
      { id: 'survive-60', name: 'いきのこり', desc: '60びょう いきのびた', secret: true },
      { id: 'score-hi', name: 'ダブルキャッチの達人', desc: '600点いじょう とった', secret: true },
    ],
    icon: { emoji: '🐰' },
    addedIn: '0.35.0',
    load: () => import('./double-rabbit/game'),
  },
  {
    id: 'rhythm-pop',
    no: 32,
    title: 'リズムでポン',
    kana: 'りずむでぽん',
    description: '上から おちてくる 音符を、リングに ぴったり重なった しゅんかんにタップ！ぴったり判定で 高得点の リズムゲーム。',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 1800, silver: 3500, gold: 5500 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '音符●が 下のリングに ぴったり重なった しゅんかんにタップ！「ぴったり」100点・「ナイス」60点。れんぞくで あてると コンボボーナス！',
      controls: [
        '左レーンの音符：画面の 左はんぶんをタップ',
        '右レーンの音符：画面の 右はんぶんをタップ',
        'テンポが はやいほど 音符が ふえて 高得点のチャンス',
      ],
      tips: [
        'リングの 少し手前で かまえて、重なる瞬間に ポン！',
        'あわてて 連打すると「空振り」で コンボが切れちゃう',
        'ヒットすると 音が鳴るよ（左=ド・右=ソ）。音でも リズムを つかもう',
      ],
    },
    achievements: [
      { id: 'first-pon', name: 'はじめてのポン', desc: '「ぴったり」を出した' },
      { id: 'combo-20', name: 'ノリノリ', desc: '20コンボ つなげた' },
      { id: 'perfect-20', name: 'ぴったりずき', desc: '1プレイで「ぴったり」を20回 出した' },
      { id: 'fast-clear', name: 'はやいテンポの達人', desc: '「はやい」で 30この音符に あてた' },
      { id: 'full-combo', name: 'フルコンボ！', desc: '1曲を みのがし・空振りゼロで えんそうした', secret: true },
      { id: 'score-hi', name: 'リズムチャンピオン', desc: '4500点いじょう とった', secret: true },
    ],
    icon: { emoji: '🎵' },
    addedIn: '0.35.0',
    load: () => import('./rhythm-pop/game'),
  },
  {
    id: 'flash-sum',
    no: 33,
    title: 'ピカッとたしざん',
    kana: 'ぴかっとたしざん',
    description: '1つずつ 光って消える 数字を あたまの中で たしていく 暗算メモリー。ラウンドが すすむほど はやく・多くなる！',
    category: 'memory',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 350, silver: 700, gold: 1100 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'ピカッと出て 消えていく数字を、あたまの中で どんどん たしていこう。ぜんぶ消えたら「たした答え」を 4つから えらぶ！全10ラウンド・まちがい3回で おしまい。',
      controls: [
        '数字が出ているあいだは よーく見る（メモは なしだよ！）',
        '「？」が出たら 4つのボタンから 答えをタップ',
        'むずかしさで 数の大きさが かわる（やさしい=1〜9）',
      ],
      tips: [
        'こえに出さず あたまの中で「いま いくつ」を となえつづけよう',
        'れんぞく正解の ボーナスが おいしい。おちついて！',
        'まちがえても だいじょうぶ。のこりの ラウンドで とりかえそう',
      ],
    },
    achievements: [
      { id: 'first-sum', name: 'はじめてのたしざん', desc: 'ラウンドに 正解した' },
      { id: 'streak-5', name: 'れんぞくメモリー', desc: '5ラウンド れんぞくで 正解した' },
      { id: 'hard-5', name: 'あんざんはかせ', desc: '「むずかしい」で 5ラウンド 正解した' },
      { id: 'count-8', name: 'おぼえた8こ', desc: '8この数字の ラウンドに 正解した', secret: true },
      { id: 'perfect-10', name: 'パーフェクトブレイン', desc: '10ラウンド ぜんぶ 正解した', secret: true },
      { id: 'score-hi', name: 'たしざんチャンピオン', desc: '1200点いじょう とった', secret: true },
    ],
    icon: { emoji: '➕' },
    addedIn: '0.35.0',
    load: () => import('./flash-sum/game'),
  },
  {
    id: 'box-push',
    no: 34,
    title: 'はこおしパズル',
    kana: 'はこおしぱずる',
    description: '📦はこを 押して ぜんぶ⭐の上へ！はこは 引けないから、押しこむ前に 1手先を 考える おかたづけパズル。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 160, silver: 280, gold: 400 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: '🐶を うごかして 📦はこを 押し、ぜんぶの はこを ⭐の上に のせよう！はこは 押せるけど 引けないよ。',
      controls: [
        'スワイプ（上下左右）または 下の矢印ボタン：1マス すすむ',
        'はこの うしろから 押すと はこが 動く',
        '「まった」で 1手もどす／「やりなおし」で 最初から',
      ],
      tips: [
        'かべぎわ・かどに 押しこむと 動かせなくなる！押す前に かんがえよう',
        '⭐の どれに どの📦を 入れるか、先に きめると らく',
        'まった を使わず とけたら ボーナス！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのおかたづけ', desc: 'はじめて そうこを かたづけた' },
      { id: 'clear-normal', name: 'そうこばんちょう', desc: '「ふつう」を クリアした' },
      { id: 'clear-hard', name: 'そうこマイスター', desc: '「むずかしい」を クリアした' },
      { id: 'no-undo', name: 'まったいらず', desc: '「まった」も「やりなおし」も 使わずに クリアした' },
      { id: 'speedy', name: 'そくたつびん', desc: '60びょう以内に クリアした', secret: true },
      { id: 'all-levels', name: 'ぜんそうこ制覇', desc: 'ぜんぶの むずかしさで クリアした', secret: true },
    ],
    icon: { emoji: '📦' },
    addedIn: '0.35.0',
    load: () => import('./box-push/game'),
  },
  {
    id: 'number-touch',
    no: 35,
    title: 'すうじタッチ',
    kana: 'すうじたっち',
    description: 'ふわふわ うごきまわる 数字を、1→2→3…の順に さがして タッチ！タイムをきそう 目と指の しゅんぱつゲーム。',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'timeMs',
    medals: { bronze: 30_000, silver: 20_000, gold: 13_000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'ばらばらに うかんだ数字を、1から順番に ぜんぶタッチ！かかった時間が みじかいほど すごい。数字は ゆっくり うごきまわるよ。',
      controls: [
        '「つぎ」に出ている数字を さがしてタップ',
        '順番を まちがえると +2びょうの ペナルティ',
        'むずかしさで 数字のかず（12/18/25）と はやさが 上がる',
      ],
      tips: [
        'つぎの数字を タッチしながら、その つぎを 目でさがそう',
        'あわてて おてつきすると 大きなロス。たしかめてから！',
        'まずは「れんしゅう」で 金メダルタイムに ちょうせん',
      ],
    },
    achievements: [
      { id: 'first-finish', name: 'はじめてのゴール', desc: 'さいごの数字まで タッチした' },
      { id: 'no-miss', name: 'おてつきなし', desc: 'おてつき0で ゴールした' },
      { id: 'clear-normal', name: 'うごくすうじ', desc: '「ふつう」を ゴールした' },
      { id: 'clear-hard', name: 'めまぐるしい', desc: '「むずかしい」を ゴールした' },
      { id: 'quick-5', name: 'そくどうスタート', desc: 'さいしょの5こを 5びょう以内に タッチした', secret: true },
      { id: 'speedy', name: 'そくたつタッチ', desc: '15びょう以内に ゴールした', secret: true },
    ],
    icon: { emoji: '👆' },
    addedIn: '0.35.0',
    load: () => import('./number-touch/game'),
  },
  {
    id: 'one-stroke',
    no: 36,
    title: 'ひとふでがき',
    kana: 'ひとふでがき',
    description: '1本の線で マスをぜんぶ通る「一筆書き」パズル。岩をよけて、交差せずに かききれるかな？3もん連続チャレンジ！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 350, silver: 600, gold: 850 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: '岩🪨いがいのマスを、1本の線で ぜんぶ通ろう！線は じぶんと交差できないよ。3もんクリアで完走！',
      controls: [
        'マスをなぞる：線がのびる（どのマスから始めてもOK）',
        '線を逆になぞる：そのぶん もどして かきなおせる',
        '「やりなおし」：この問題の線を ぜんぶけす',
      ],
      tips: [
        'いきどまりに なったら、少しもどって べつの道へ',
        'はしっこや 岩のまわりから 考えると 道が見えてくる',
        'はやくかききるほど ボーナス！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのひとふで', desc: '1もん かききった' },
      { id: 'all-rounds', name: '3もんかんそう', desc: '1プレイで 3もん ぜんぶかききった' },
      { id: 'no-retry', name: 'かきなおしいらず', desc: '「やりなおし」を使わずに 3もん完走した' },
      { id: 'speedy', name: 'いっきがき', desc: '1もんを 20びょう以内で かききった', secret: true },
      { id: 'hard-clear', name: 'むずかしいマスター', desc: '「むずかしい」で 3もん完走した' },
      { id: 'all-presets', name: 'ひとふでのたつじん', desc: 'ぜんぶのむずかしさで 完走した', secret: true },
    ],
    icon: { emoji: '✍️' },
    addedIn: '0.50.0',
    load: () => import('./one-stroke/game'),
  },
  {
    id: 'candy-sort',
    no: 37,
    title: 'キャンディふりわけ',
    kana: 'きゃんでぃふりわけ',
    description: 'ころがってくるキャンディを、分かれ道のゲートを切りかえて 同じ色のビンへ！どんどん はやくなる おおいそがし仕分けゲーム。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 500, gold: 800 },
    timeToPlay: 'short',
    help: {
      goal: 'ころがってくるキャンディを、同じ色のビンに 入れよう！分かれ道の ゲートをタップすると 左右が切りかわるよ。60びょう しょうぶ。',
      controls: [
        'まるい ゲートをタップ：矢印の向きが 切りかわる',
        'キャンディは 矢印の向きに ころがっていく',
        'ちがう色のビンに 入れると ライフ−1（3つで おしまい）',
      ],
      tips: [
        'ビンの色の ならびは 毎回ちがう。さいしょに かくにん！',
        '先に来るキャンディから じゅんばんに ゲートを合わせよう',
        '🌈レインボーは どのビンでもOK（+30）。れんぞく成功で コンボボーナス！',
      ],
    },
    achievements: [
      { id: 'debut-15', name: 'ふりわけデビュー', desc: '1プレイで 15こ ふりわけた' },
      { id: 'combo-10', name: 'コンボめいじん', desc: '10れんぞくで 正しく ふりわけた' },
      { id: 'sort-40', name: 'おおいそがし', desc: '1プレイで 40こ ふりわけた' },
      { id: 'no-miss-25', name: 'ミスなしのたつじん', desc: 'ミス0のまま 25こ ふりわけた' },
      { id: 'rainbow-5', name: 'にじいろコレクター', desc: '1プレイで 🌈を5こ ふりわけた', secret: true },
      { id: 'score-hi', name: 'キャンディチャンピオン', desc: '700てん いじょう とった', secret: true },
    ],
    icon: { emoji: '🍬' },
    addedIn: '0.50.0',
    load: () => import('./candy-sort/game'),
  },
  {
    id: 'tightrope',
    no: 38,
    title: 'つなわたりバランス',
    kana: 'つなわたりばらんす',
    description: '高い高い つなの上を バランスをとりながら すすもう！かたむいたら ぎゃくがわを おして たてなおし。風にもまけずに 何メートル あるける？',
    category: 'sensor',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 300, silver: 700, gold: 1200 },
    timeToPlay: 'short',
    help: {
      goal: 'つなの上を 自動で歩いていくよ。たおれないように バランスをとって、できるだけ 遠くまで すすもう！40°かたむくと 落ちちゃう。200mで ゴール！',
      controls: [
        'かたむいた side（がわ）と ぎゃくの画面はんぶんを おしっぱなし：たてなおす',
        'スマホを ぎゃくに かたむけてもOK（センサーがなくてもあそべる）',
        '🌬マークが出たら 風がくる合図。先に そなえよう！',
      ],
      tips: [
        'ちょっとの かたむきのうちに こまめに なおすのが コツ',
        '風は 予告のあとに ドンと押してくる。ぎゃくがわに かたむけて まちかまえよう',
        '遠くへ行くほど 歩くのが はやく・たおれやすくなる',
      ],
    },
    achievements: [
      { id: 'first-10', name: 'はじめの10m', desc: '10m あるいた' },
      { id: 'dist-50', name: 'つなわたりじょうず', desc: '50m あるいた' },
      { id: 'dist-100', name: 'つなわたりめいじん', desc: '100m あるいた', secret: true },
      { id: 'recover-8', name: 'たてなおしめいじん', desc: '1プレイで 8回 たてなおした' },
      { id: 'tilt-only-50', name: 'かたむきマスター', desc: '画面を おさずに かたむきだけで 50m あるいた', secret: true },
      { id: 'goal-200', name: 'ゴールのけしき', desc: '200mの ゴールに たどりついた', secret: true },
    ],
    icon: { emoji: '🎪' },
    addedIn: '0.50.0',
    load: () => import('./tightrope/game'),
  },
  {
    id: 'trace-shape',
    no: 39,
    title: 'まねっこおえかき',
    kana: 'まねっこおえかき',
    description: 'うすく見える お手本の形を、ゆびで 一筆なぞって さいてん！まる・ほし・うずまき…きみは 何点かける？',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 450, silver: 650, gold: 850 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'うすい線の お手本を、ゆびで なぞって まねしよう！「せいかくさ」と「ぜんぶなぞれたか」で 採点されるよ。全5もん・各200点満点。',
      controls: [
        'ゆびで お手本の上を なぞる（一筆がき）',
        'ゆびを はなすと さいてん！とちゅうで離すと そこまでで判定',
        'ちょっと ふれただけなら ノーカウント（やりなおせる）',
      ],
      tips: [
        'ゆっくり ていねいに なぞるほうが 高得点',
        'とぎれず 最後まで なぞりきるのが だいじ',
        '「ほし」と「うずまき」は 超むずかしい。💮はなまる（170点〜）を ねらえ！',
      ],
    },
    achievements: [
      { id: 'first-hanamaru', name: 'はじめてのはなまる', desc: '💮はなまる（170点いじょう）を とった' },
      { id: 'hanamaru-3', name: 'はなまるコレクター', desc: '1プレイで 💮を3回 とった' },
      { id: 'star-master', name: 'ほしなぞりめいじん', desc: '「ほし」で 💮を とった', secret: true },
      { id: 'spiral-master', name: 'うずまきめいじん', desc: '「うずまき」で 💮を とった', secret: true },
      { id: 'total-700', name: 'おえかきじょうず', desc: 'ごうけい 700点いじょう とった' },
      { id: 'total-900', name: 'てんさいアーティスト', desc: 'ごうけい 900点いじょう とった', secret: true },
    ],
    icon: { emoji: '✏️' },
    addedIn: '0.50.0',
    load: () => import('./trace-shape/game'),
  },
  {
    id: 'charge-jump',
    no: 40,
    title: 'ためてジャンプ',
    kana: 'ためてじゃんぷ',
    description: '長おしで パワーをためて、はなした瞬間 カエルがジャンプ！ちょうどいい力かげんで つぎの足場へ。だんだん せまく・遠く・うごく！',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 400, gold: 650 },
    timeToPlay: 'short',
    help: {
      goal: '画面を 長おしして パワーをためて、はなすと ジャンプ！つぎの足場に 着地しつづけよう。おちたら おしまい。',
      controls: [
        '画面を おしっぱなし：パワーが たまる（ゲージを見て！）',
        'ゆびを はなす：ジャンプ！おした長さで とぶ距離が きまる',
        '足場の まん中（金色ゾーン）に 乗ると「ピタッ！」ボーナス',
      ],
      tips: [
        'ちかい足場は ちょっとだけ、とおい足場は ぐーっと ためる',
        '⇄マークの 足場は うごく！着地する瞬間の 場所を ねらおう',
        'ピタッを つづけると コンボで どんどん 高得点',
      ],
    },
    achievements: [
      { id: 'first-pita', name: 'はじめてのピタッ', desc: 'まん中ゾーンに 着地した' },
      { id: 'land-10', name: 'ぴょんぴょん', desc: '1プレイで 足場10こ すすんだ' },
      { id: 'land-25', name: 'ジャンプめいじん', desc: '1プレイで 足場25こ すすんだ' },
      { id: 'pita-combo-5', name: 'ピタッの神わざ', desc: '5れんぞくで ピタッ！', secret: true },
      { id: 'moving-8', name: 'うごく足場ずき', desc: 'うごく足場に 8回 着地した' },
      { id: 'score-hi', name: 'ジャンプチャンピオン', desc: '500てん いじょう とった', secret: true },
    ],
    icon: { emoji: '🐸' },
    addedIn: '0.50.0',
    load: () => import('./charge-jump/game'),
  },
  {
    id: 'flap-flight',
    no: 41,
    title: 'ぱたぱたフライト',
    kana: 'ぱたぱたふらいと',
    description: 'タップで はばたく ひよこを あやつり、岩柱のすきまを くぐりぬけろ！ぶつかったら 即おしまいの ちょう高難度ワンボタン飛行。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 80, silver: 200, gold: 350 },
    timeToPlay: 'short',
    help: {
      goal: 'タップするたび ひよこが はばたいて上がるよ。岩柱のすきまを くぐりぬけて、できるだけ 遠くまで 飛ぼう！岩・地面・天井に ふれたら おしまい。',
      controls: [
        '画面タップ：はばたく（上がる）',
        'なにもしない：おちていく',
        '⭐を とると ボーナス（+15）',
      ],
      tips: [
        'ちいさく こまめに はばたくのが あんてい のコツ',
        'すきまは だんだん せまく・はやく・後半は 上下にうごく！',
        '⭐は ムリしてまで とらなくて いい。まずは 生きのこる！',
      ],
    },
    achievements: [
      { id: 'first-5', name: 'はじめてのそら', desc: 'ゲートを 5こ くぐった' },
      { id: 'gate-15', name: 'ひよこパイロット', desc: '1プレイで ゲート15こ' },
      { id: 'gate-30', name: 'そらのおうじゃ', desc: '1プレイで ゲート30こ', secret: true },
      { id: 'star-8', name: 'スターあつめ', desc: '1プレイで ⭐を8こ とった' },
      { id: 'total-100', name: 'つうさん100ゲート', desc: 'あわせて 100こ くぐった', secret: true },
      { id: 'score-hi', name: 'フライトチャンピオン', desc: '400てん いじょう とった', secret: true },
    ],
    icon: { emoji: '🐤' },
    addedIn: '0.50.0',
    load: () => import('./flap-flight/game'),
  },
  {
    id: 'buzz-wire',
    no: 42,
    title: 'ビリビリワイヤー',
    kana: 'びりびりわいやー',
    description: '電気のワイヤーめいろを、ふれないように ゆびで さいごまで なぞりきれ！手がふるえる 超精密ドラッグの3コース。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 500, gold: 750 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ひかる たまを ゆびでうごかして、ワイヤーの みちから はみ出さずに ゴール🏁まで なぞろう！ぜんぶで3コース。はみ出すと ビリッ⚡（3回で おしまい）。',
      controls: [
        'たまにタッチ → そのまま ゆっくり なぞる（たまは ゆびの少し上に うくよ）',
        'ビリッとしたら 直前の ◎チェックポイントから さいかい',
        'つかれたら ゆびを はなして 休けいOK（タッチで さいかい）',
      ],
      tips: [
        'はやく動かすほど はみ出しやすい。「ゆっくり ていねいに」が さいそく',
        'コースは だんだん 細く・うねうねに なる',
        'ビリなしクリアと はやさで 大ボーナス！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのかんつう', desc: 'コース1を なぞりきった' },
      { id: 'clear-2', name: 'ほそみちマスター', desc: 'コース2を なぞりきった' },
      { id: 'clear-3', name: 'ワイヤーのたつじん', desc: 'コース3まで ぜんぶ なぞりきった' },
      { id: 'no-zap-course', name: 'ノービリ', desc: '1コースを ビリなしで なぞりきった' },
      { id: 'no-zap-all', name: 'かんぺきな手さばき', desc: '3コースぜんぶ ビリなし', secret: true },
      { id: 'speedy', name: 'いそぎの職人', desc: '1コースを 30びょう以内で なぞりきった', secret: true },
    ],
    icon: { emoji: '⚡' },
    addedIn: '0.50.0',
    load: () => import('./buzz-wire/game'),
  },
  {
    id: 'instant-number',
    no: 43,
    title: 'いっしゅんナンバー',
    kana: 'いっしゅんなんばー',
    description: '一瞬だけ見える数字の「場所」をおぼえて、かくれたら 1から順にタップ！ラウンドがすすむほど 数がふえて 見える時間が縮む、記憶の限界チャレンジ。',
    category: 'memory',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 400, silver: 800, gold: 1200 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'バラバラにおかれた数字が 一瞬でかくれるよ。場所をおぼえて、1→2→3…の順に ぜんぶタップ！全10ラウンド・おてつき2回で おしまい。',
      controls: [
        '数字が見えているあいだに 場所をおぼえる',
        'かくれたら おぼえた順に タップ',
        'じしんがあれば「1」を早おし→その瞬間にかくれて スピードボーナスをねらえる',
      ],
      tips: [
        '「かたまり」や「ならび」で おぼえると 強い（例: 左下に1と4）',
        'はやく おしおわるほど ボーナスアップ',
        'さいごは 9こ×一瞬。チンパンジーなみの記憶に ちょうせん！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのきおく', desc: 'ラウンドを クリアした' },
      { id: 'clear-7', name: '7このきおく', desc: '数字7この ラウンドをクリアした' },
      { id: 'clear-9', name: '9このきおく', desc: '数字9この ラウンドをクリアした', secret: true },
      { id: 'speed-2s', name: 'いっしゅんの達人', desc: '1ラウンドを 2びょう以内に おしおえた' },
      { id: 'no-miss-all', name: 'かんぺきメモリー', desc: 'おてつき0で 10ラウンド完走した', secret: true },
      { id: 'total-1000', name: 'きおくチャンピオン', desc: '1プレイで 1000てん とった', secret: true },
    ],
    icon: { emoji: '🧠' },
    addedIn: '0.50.0',
    load: () => import('./instant-number/game'),
  },
  {
    id: 'echo-drum',
    no: 44,
    title: 'ものまねドラム',
    kana: 'ものまねどらむ',
    description: 'お手本のリズムを 聞いておぼえて、同じ「間」で たたき返せ！ズレをミリ秒判定する 本気のリズム記憶ゲーム。',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 350, silver: 700, gold: 1000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'お手本のリズム（音と光）をおぼえて、同じリズムで 画面をたたこう！1打目が基準になって、2打目からの「間」のズレで判定されるよ。全10もん・ミス3回で おしまい。',
      controls: [
        'お手本のあいだは よくきく（👂）',
        '「きみのばん！」で 画面のどこでもタップ＝ドラム',
        'ズレ55ms以内=ぴったり(+20)／115ms以内=おしい(+10)／それ以上=ミス',
      ],
      tips: [
        '心の中で「タン・タタ・ターン」と歌いながら きくと おぼえやすい',
        '1打目は いつたたいてもOK。そこからの「間」が しょうぶ',
        'ぜんぶ「ぴったり」なら 大ボーナス！後半は 8分音符や 付点のひっかけも',
      ],
    },
    achievements: [
      { id: 'first-perfect', name: 'はじめてのかんぺき', desc: '1もんを ぜんぶ「ぴったり」でたたいた' },
      { id: 'reach-5', name: 'リズムずき', desc: 'おだい5まで すすんだ' },
      { id: 'clear-all', name: '10もん完走', desc: 'さいごの おだいまで たたききった' },
      { id: 'perfect-20', name: 'ぴったりコレクター', desc: '1プレイで「ぴったり」を20回 出した' },
      { id: 'no-miss', name: 'ノーミスドラマー', desc: 'ミス0で 10もん完走した', secret: true },
      { id: 'score-hi', name: 'リズムのしはいしゃ', desc: '1000てん いじょう とった', secret: true },
    ],
    icon: { emoji: '🥁' },
    addedIn: '0.50.0',
    load: () => import('./echo-drum/game'),
  },
  {
    id: 'switch-off',
    no: 45,
    title: 'ぜんけしスイッチ',
    kana: 'ぜんけしすいっち',
    description: 'おすと「十字に はんてん」するスイッチで、ぜんぶの明かりを消せ！さいたん手数をねらう 頭脳ちょっかんパズルの決定版。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 300, silver: 600, gold: 850 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'マスをおすと そのマスと上下左右の明かりが はんてんするよ。ぜんぶの💡を消したらクリア！3もん連続・「さいたん」手数ぴったりなら 大ボーナス。',
      controls: [
        'マスをタップ：十字に はんてん',
        '「やりなおし」：さいしょの盤にもどす（手数は つづき）',
        'さいたん手数は 画面の上に出ているよ',
      ],
      tips: [
        '同じマスを2回おすと もとどおり＝おすのは1回ずつでいい',
        '「上の行の明かりは、下の行のスイッチで消す」が 基本ワザ',
        'まずは4×4でコツをつかもう。5×5のさいたんは 本気でむずかしい！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのぜんけし', desc: '1もん クリアした' },
      { id: 'par-round', name: 'さいたんヒット', desc: 'さいたん手数ぴったりで クリアした' },
      { id: 'speedy', name: 'そくけし', desc: '1もんを 60びょう以内で クリアした' },
      { id: 'clear-all', name: '3もん完走', desc: 'さいごの もんまで ぜんけしした' },
      { id: 'par-all', name: 'さいたんマスター', desc: '3もんぜんぶ さいたん手数で クリアした', secret: true },
      { id: 'total-900', name: 'スイッチチャンピオン', desc: '1プレイで 900てん とった', secret: true },
    ],
    icon: { emoji: '💡' },
    addedIn: '0.50.0',
    load: () => import('./switch-off/game'),
  },
  {
    id: 'shake-juice',
    no: 46,
    title: 'シェイクジュース',
    kana: 'しぇいくじゅーす',
    description: 'スマホをふって ジュースづくり！レシピの「ちょうどいい強さ」をキープしてミックス。ふりすぎると あわだって こぼれちゃう！',
    category: 'sensor',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    medals: { bronze: 330, silver: 450, gold: 560 },
    timeToPlay: 'short',
    help: {
      goal: 'レシピの「ちょうどいい強さ」で スマホをふって、ミックスを100%にしよう！ぜんぶで3杯。ふりすぎると あわが立って、あふれると こぼれるよ。',
      controls: [
        'スマホを ふる：メーターの みどりの帯に 入るように！',
        'タップ連打でもOK（れんだの速さ＝つよさ）',
        'あわが 立ってきたら いったん 手をゆるめよう',
      ],
      tips: [
        'レシピごとに ちょうどいい強さが ちがう（そーっと〜つよく）',
        'メーターを 見ながら 一定のリズムで ふるのが コツ',
        'はやく作るほど ボーナス。こぼさなければ さらに +40！',
      ],
    },
    achievements: [
      { id: 'first-juice', name: 'はじめてのいっぱい', desc: 'ジュースを 1杯 かんせいさせた' },
      { id: 'all-juice', name: 'ジュースやさん', desc: '3杯 ぜんぶ かんせいさせた' },
      { id: 'no-spill', name: 'こぼしませんでした', desc: '1回もこぼさずに 3杯 つくった' },
      { id: 'gentle-pro', name: 'そーっとのたつじん', desc: '「そーっと」レシピを こぼさず つくった' },
      { id: 'quick-12', name: 'はやづくり', desc: '1杯を 12びょう以内で つくった' },
      { id: 'shake-only', name: 'シェイクマイスター', desc: 'タップを使わず ふるだけで 3杯 つくった', secret: true },
    ],
    icon: { emoji: '🥤' },
    addedIn: '0.50.0',
    load: () => import('./shake-juice/game'),
  },
  {
    id: 'coloring',
    no: 47,
    title: 'ぬりえタッチ',
    kana: 'ぬりえたっち',
    description: '数字とおなじ色をえらんで、マスをタップでぬっていく デジタルぬりえ。ぜんぶぬると かわいいドット絵が完成！',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 230, silver: 300, gold: 370 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'パレットで色をえらんで、おなじ数字のマスをタップでぬろう！ぜんぶぬると ドット絵が完成するよ。',
      controls: [
        '下のパレットをタップ：色をえらぶ（丸の中が 数字）',
        'おなじ数字のマスをタップ：ぬれる！',
        'ちがう数字のマスは ぷるぷるっとするだけ（へいき へいき）',
      ],
      tips: [
        '1つの色を ぜんぶぬると、つぎの色に 自動で かわるよ',
        'はやく・まちがえずに ぬると ボーナスアップ',
        '絵は「りんご・ちょうちょ・おうち」の3まい。ぜんぶ完成させよう！',
      ],
    },
    achievements: [
      { id: 'first-complete', name: 'はじめてのさくひん', desc: 'ぬりえを 1まい 完成させた' },
      { id: 'no-miss', name: 'ていねいなぬりえ', desc: 'まちがい0で 完成させた' },
      { id: 'speedy-90', name: 'はやぬり', desc: '90びょう以内に 完成させた' },
      { id: 'streak-20', name: 'ぬりぬりリズム', desc: 'まちがえずに れんぞく20マス ぬった' },
      { id: 'all-arts', name: 'てんらんかい', desc: '3しゅるいの絵を ぜんぶ 完成させた' },
      { id: 'perfect', name: 'かんぺきアーティスト', desc: 'まちがい0＆90びょう以内で 完成させた', secret: true },
    ],
    icon: { emoji: '🎨' },
    addedIn: '0.50.0',
    load: () => import('./coloring/game'),
  },
  {
    id: 'shopping-memory',
    no: 48,
    title: 'おつかいメモリー',
    kana: 'おつかいめもりー',
    description: 'おつかいリストを おぼえて、お店の棚から 同じ品をえらぼう！ダミーにまどわされない リスト記憶ゲーム。',
    category: 'memory',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 280, silver: 420, gold: 550 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '「おつかいリスト」（3〜6品）をおぼえて、棚から リストにあった品だけを タップ！じゅんばんは じゆう。全5回のおつかい。',
      controls: [
        'リストが出ているあいだに しっかり おぼえる',
        '「おぼえた！」で 早めに お店へ 行ってもOK',
        '棚で リストの品をタップ（ちがう品は ぷるぷるっとするだけ）',
      ],
      tips: [
        '「くだもの2つと のみもの」みたいに まとめて おぼえると 強い',
        'にた品（🍎と🍊など）の ひっかけに 気をつけて',
        'はやく・まちがえずに あつめると ボーナス！',
      ],
    },
    achievements: [
      { id: 'first-round', name:'はじめてのおつかい', desc: 'おつかいを 1回 かんりょうした' },
      { id: 'no-miss-round', name: 'たのまれじょうず', desc: 'まちがえずに 1回の おつかいを かんりょうした' },
      { id: 'list-6', name: 'おぼえる天才', desc: '6品の おつかいを かんりょうした' },
      { id: 'speedy-round', name: 'はやいおつかい', desc: '1回の おつかいを 8びょう以内で かんりょうした' },
      { id: 'all-rounds', name: '5回のおつかい', desc: 'さいごの おつかいまで かんりょうした' },
      { id: 'no-miss-all', name: 'かんぺきなおつかい', desc: 'まちがい0で 5回ぜんぶ かんりょうした', secret: true },
    ],
    icon: { emoji: '🛒' },
    addedIn: '0.50.0',
    load: () => import('./shopping-memory/game'),
  },
  {
    id: 'jump-rope',
    no: 49,
    title: 'ぴょんぴょんなわとび',
    kana: 'ぴょんぴょんなわとび',
    description: '回ってくるなわに合わせて タップでジャンプ！とぶほど なわが はやくなる、リズムなわとびチャレンジ。',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 200, silver: 450, gold: 800 },
    timeToPlay: 'short',
    help: {
      goal: 'なわが 足もとを通る しゅんかんに タップでジャンプ！ひっかからずに 何回とべるかな？3回つまずくと おしまい。',
      controls: [
        '画面タップ：ジャンプ（とんでいる間は 連打できないよ）',
        '足もとが 金色に ひかったら タップ！ひかっている間なら かならず まにあうよ',
        'つまずいても だいじょうぶ。なわは てっぺんから 再スタート',
      ],
      tips: [
        'とぶほど なわが はやくなる！リズムに乗ろう',
        'れんぞくで とぶと コンボで 1回の点数アップ（さいだい+10）',
        '「トン…トン…」と 声に出すと タイミングが つかみやすい',
      ],
    },
    achievements: [
      { id: 'first-10', name: 'なわとびデビュー', desc: '10回 とんだ' },
      { id: 'jump-30', name: 'ぴょんぴょんマスター', desc: '1プレイで 30回 とんだ' },
      { id: 'jump-60', name: 'なわとびのたつじん', desc: '1プレイで 60回 とんだ', secret: true },
      { id: 'combo-25', name: 'ノンストップ25', desc: '25れんぞくで とんだ' },
      { id: 'no-trip-30', name: 'ひっかからずに30', desc: 'つまずき0のまま 30回 とんだ' },
      { id: 'score-hi', name: 'なわとびチャンピオン', desc: '700てん いじょう とった', secret: true },
    ],
    icon: { emoji: '🪢' },
    addedIn: '0.50.0',
    load: () => import('./jump-rope/game'),
  },
  {
    id: 'daruma-run',
    no: 50,
    title: 'だるまさんがころんだ',
    kana: 'だるまさんがころんだ',
    description: 'おにが言っている間だけ すすんで、振り向いた瞬間に ピタッと止まれ！フェイントにドキドキの 伝統あそび。',
    category: 'reflex',
    orientation: 'portrait',
    scoring: 'points',
    medals: { bronze: 250, silver: 400, gold: 520 },
    timeToPlay: 'short',
    help: {
      goal: 'おにが「だるまさんがころんだ」と言っている間だけ 画面をおして前へ！言い終わって 振り向いた瞬間に おしていたら つかまる（3回でおしまい）。40m先の おににタッチで ゴール！',
      controls: [
        '画面を おしっぱなし：前に すすむ',
        'おにが 振り向いたら すぐ 手をはなす！（ちょっとだけ 猶予あり）',
        'おにが 背中を向けたら また すすめる',
      ],
      tips: [
        '読み上げの はやさは 毎回ちがう。声の リズムをよく聞いて…じゃなくて よく見て！',
        'とちゅうで 止まる「フェイント」あり。止まっても 振り向かないよ',
        'つかまらず・はやくタッチするほど 高得点！',
      ],
    },
    achievements: [
      { id: 'first-goal', name: 'はじめてのタッチ', desc: 'おにに タッチした' },
      { id: 'no-caught', name: 'そーっとのぷろ', desc: '1回も つかまらずに タッチした' },
      { id: 'speedy-35', name: 'いそぎあし', desc: '35びょう以内に タッチした' },
      { id: 'dash-6', name: 'おおまたダッシュ', desc: '1回の読み上げで 6m いじょう すすんだ' },
      { id: 'goal-3', name: 'だるまさんのともだち', desc: 'あわせて 3回 タッチした', secret: true },
      { id: 'perfect', name: 'かんぺきなしのびあし', desc: 'つかまらず 35びょう以内で タッチした', secret: true },
    ],
    icon: { emoji: '🙈' },
    addedIn: '0.50.0',
    load: () => import('./daruma-run/game'),
  },
  {
    id: 'tic-tac-toe',
    no: 51,
    title: 'まるばつゲーム',
    kana: 'まるばつげーむ',
    description: 'たて・よこ・ななめに 〇か×を3つ そろえたら かち！CPUと5番勝負。先手はこうたい、つよいCPUは まけしらず。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    // 1局=勝ち(よわい100/ふつう120/つよい160)・引分(40/55/80)。理論最大=ふつう5勝600
    // （つよいは完全読みで勝てない＝引分400が上限）。金520はふつうで4勝以上いれば届く
    medals: { bronze: 200, silver: 380, gold: 520 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'たて・よこ・ななめ どれかに 自分のしるしを 3つ ならべたら かち！ぜんぶで5局、先手（〇）は1局ごとに こうたいするよ。',
      controls: [
        'あいているマスをタップ：しるしをおく',
        '自分のしるしは 局の はじめに 教えてくれるよ（〇か×）',
        '5局の 合計スコアで しょうぶ',
      ],
      tips: [
        'まん中は 4本のラインが とおる いちばん強い場所',
        'あいてが 2つ ならべたら 3つめを ふさごう',
        '2つの「リーチ」を 同時に つくると ふさぎきれない！',
      ],
    },
    achievements: [
      { id: 'first-win', name: 'はつしょうり', desc: '1局 勝った' },
      { id: 'sweep', name: 'ぜんしょう', desc: '5番勝負で 5局ぜんぶ 勝った' },
      { id: 'no-loss', name: 'むはい', desc: '5番勝負を 1回も まけずに おえた', secret: true },
      { id: 'fork-win', name: 'ダブルリーチ', desc: '2つのリーチを 同時につくって 勝った', secret: true },
      { id: 'draw-strong', name: 'つよいと ひきわけ', desc: 'つよいCPUと 引き分けた' },
      { id: 'total-15', name: 'まるばつはかせ', desc: 'あわせて 15局 勝った', secret: true },
    ],
    icon: { emoji: '⭕', svg: ICON_TICTACTOE },
    addedIn: '0.67.0',
    load: () => import('./tic-tac-toe/game'),
  },
  {
    id: 'gem-match',
    no: 52,
    title: 'キラキラマッチ3',
    kana: 'きらきらまっちすりー',
    description: 'となりの宝石を 入れ替えて、たて・よこに 3つそろえて消そう！れんさで 大量点をねらう 30手スコアアタック。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    // 30手・れんさ倍率×最大5。やさしい(5色)がいちばん そろいやすく点も伸びる＝理論上限が高い。
    // E2E計測で貪欲プレイ 5000点前後 → 金4500は上級者の目標として到達可能
    medals: { bronze: 1500, silver: 3000, gold: 4500 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'となりの宝石を 入れ替えて、たて か よこに 同じ色を 3つ以上 ならべて消そう！30手のあいだに たくさん点をとろう。',
      controls: [
        '宝石をタップ→となりの宝石をタップ：入れ替え',
        'そろわない入れ替えは 手を つかわない（元にもどる）',
        '色の数（むずかしさ）は 開始前に えらべる',
      ],
      tips: [
        '消えて 落ちてきた宝石が また そろうと「れんさ」で 点が どんどん ばいに！',
        '4つ・5つ まとめて消すと ボーナス点',
        '手を うごかす前に、大きく そろう場所を さがそう',
      ],
    },
    achievements: [
      { id: 'first-match', name: 'はじめてのマッチ', desc: 'はじめて 宝石を そろえた' },
      { id: 'combo-4', name: 'フォーマッチ', desc: '4つ いじょう 一気にそろえた' },
      { id: 'big-clear', name: 'だいばくはつ', desc: '1手で 10個いじょう 消した' },
      { id: 'cascade-3', name: 'れんさマスター', desc: '1手で 3れんさ おこした', secret: true },
      { id: 'combo-5', name: 'ファイブマッチ', desc: '5つ いじょう 一気にそろえた', secret: true },
      { id: 'score-hi', name: 'キラキラめいじん', desc: '2000点 いじょう とった', secret: true },
    ],
    icon: { emoji: '💎' },
    addedIn: '0.67.0',
    load: () => import('./gem-match/game'),
  },
  {
    id: 'dot-muncher',
    no: 53,
    title: 'もぐもぐドット',
    kana: 'もぐもぐどっと',
    description: '迷路のドットを ぜんぶ食べよう！おばけに つかまらないように。⭐パワーエサで おばけを 食べられるぞ。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // ドット10・パワー50・おばけ200〜・ステージクリア+300。E2E計測で1面完食 約900点/おばけ多食で加算
    medals: { bronze: 1500, silver: 3500, gold: 6000 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '迷路の 小さなドットを ぜんぶ食べたら ステージクリア！おばけに つかまると ライフが へるよ（3つまで）。',
      controls: [
        '画面をスワイプ：もぐもぐの すすむ向きを かえる',
        '画面下の 十字ボタンでもOK',
        '⭐パワーエサを 食べると おばけが 青くなって 食べられる！',
      ],
      tips: [
        '青いおばけを 食べると 大得点（つづけて 食べるほど 高い）',
        '角を うまく つかって おばけを かわそう',
        'ステージが すすむと おばけが 増えて 速くなる',
      ],
    },
    achievements: [
      { id: 'first-dot', name: 'はじめのひとくち', desc: 'ドットを はじめて 食べた' },
      { id: 'clear-stage', name: 'ステージクリア', desc: '1ステージ 完食した' },
      { id: 'ghost-eater', name: 'おばけをパクリ', desc: '青いおばけを 食べた' },
      { id: 'ghost-combo', name: 'れんぞくパクパク', desc: '1回のフィーバーで 2匹いじょう 食べた', secret: true },
      { id: 'stage-3', name: 'ステージ3とうたつ', desc: 'ステージ3まで すすんだ', secret: true },
      { id: 'score-hi', name: 'もぐもぐめいじん', desc: '5000点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🟡' },
    addedIn: '0.67.0',
    load: () => import('./dot-muncher/game'),
  },
  {
    id: 'crane-catch',
    no: 54,
    title: 'わくわくクレーン',
    kana: 'わくわくくれーん',
    description: '動くクレーンを 景品の上で ピタッと止めてキャッチ！中心で つかむほど 運ぶとちゅうで すべりにくい。ぜんぶで8回。',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    // 8回・景品30〜200＋中心ボーナス最大25。レア(⭐120/💎200)は細い。
    // E2E計測(完全中心プレイ8連続)で553〜954点。金850は上手＋レア狙いで到達可・銀550は堅実プレイ
    medals: { bronze: 280, silver: 550, gold: 850 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '左右に動く クレーンを、ほしい景品の 上で タップして止めよう！下りて つかんで、シュートまで 運べたら ゲット。ぜんぶで8回。',
      controls: [
        '画面をタップ：クレーンを止める',
        '景品の まん中で 止めるほど つかむ力が つよい',
        'ちゅうしんを 外すと 運ぶとちゅうで すべって 落ちることも…！',
      ],
      tips: [
        '⭐や💎は 高得点だけど 細くて むずかしい',
        'まん中ぴったりで つかむと 中心ボーナス＆すべりにくい',
        '動きは だんだん 速くなる。よく見て タイミングを！',
      ],
    },
    achievements: [
      { id: 'first-get', name: 'はじめてのゲット', desc: 'はじめて 景品を とった' },
      { id: 'get-5', name: 'たくさんゲット', desc: '1プレイで 5こ とった' },
      { id: 'rare-get', name: 'レアをゲット', desc: '⭐か💎の レア景品を とった' },
      { id: 'gem-get', name: 'ダイヤをゲット', desc: '💎を とった', secret: true },
      { id: 'perfect', name: 'ドまんなか', desc: 'まん中ぴったりで つかんだ', secret: true },
      { id: 'score-hi', name: 'クレーンめいじん', desc: '700点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🕹️' },
    addedIn: '0.67.0',
    load: () => import('./crane-catch/game'),
  },
  {
    id: 'goldfish-scoop',
    no: 55,
    title: 'きんぎょすくい',
    kana: 'きんぎょすくい',
    description: 'ポイで きんぎょを すくって おわんへ！水につけすぎ・のせすぎると 紙がやぶれる。お祭りの まったりゲーム。',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    // 魚20〜80（らんちゅう80はレア）。ポイ3まい・75秒。E2Eで到達性は実証済(ボット上限5000超)。
    // 人間ペース(75秒で15〜25匹)を想定し 銅=8匹級/銀=15匹級/金=レア込みの上手なプレイ。実機で要調整
    medals: { bronze: 250, silver: 500, gold: 800 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'ポイ（網）で きんぎょを すくって、上の おわんへ はこぼう！ポイの紙は やぶれるまで 使えるよ（ぜんぶで3まい）。',
      controls: [
        '画面を ドラッグ：ポイを動かす',
        '魚の下から すくって、おわんの上へ はこぶと とくてん',
        'ポイを 水に つけている間・魚を のせすぎると 紙が やぶれる！',
      ],
      tips: [
        'そーっと 近づかないと 魚は にげちゃう',
        '一度に たくさん のせると 重くて すぐ やぶれる。よくばりすぎ ちゅうい',
        '金色の らんちゅうは レアで 高得点！',
      ],
    },
    achievements: [
      { id: 'first-catch', name: 'はじめの1ぴき', desc: 'はじめて おわんに 入れた' },
      { id: 'many-fish', name: 'たくさんすくった', desc: '1プレイで 8ひき すくった' },
      { id: 'rare-catch', name: 'らんちゅうGET', desc: '金色の らんちゅうを すくった' },
      { id: 'big-scoop', name: 'いっきに3びき', desc: '1回で 3びき いじょう はこんだ', secret: true },
      { id: 'one-poi', name: 'ポイ名人', desc: '1まい目の ポイで 5ひき すくった', secret: true },
      { id: 'score-hi', name: 'きんぎょめいじん', desc: '800点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🐠' },
    addedIn: '0.67.0',
    load: () => import('./goldfish-scoop/game'),
  },
  {
    id: 'solitaire',
    no: 56,
    title: 'ソリティア',
    kana: 'そりてぃあ',
    description: '1人でトランプ。カードを タップすると 置ける場所へ 自動でうごく やさしいクロンダイク。ぜんぶ そろえよう！',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    // 組札1枚+15・クリア+300+速さ。全クリア=52*15+300+速さ≒1000超。E2Eで到達性確認のうえ較正
    medals: { bronze: 200, silver: 500, gold: 850 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: '4つの 組札に ♠♥♦♣ ごとに A→2→3…→K の順で ぜんぶ のせたら クリア！',
      controls: [
        'カードを タップ：置ける場所へ 自動でうごく（組札ゆうせん）',
        '左上の 山札を タップ：カードを1枚 めくる（なくなったら もう一周）',
        '場札は 色ちがいで 1つずつ 小さく かさねられる',
      ],
      tips: [
        'めくり札や 場札の カードを タップすると、置けるなら すすむよ',
        'あいた列には K（キング）から おける',
        'こまったら 山札を めくって 手を さがそう',
      ],
    },
    achievements: [
      { id: 'first-foundation', name: 'はじめの1枚', desc: '組札に はじめて カードを のせた' },
      { id: 'suit-done', name: 'ワンスート完成', desc: '1つのスートを A→K そろえた' },
      { id: 'half', name: 'はんぶん', desc: '組札に 26枚 のせた' },
      { id: 'win', name: 'クリア！', desc: 'ぜんぶ そろえて クリアした' },
      { id: 'speed-win', name: 'はやわざクリア', desc: '5分いないで クリアした', secret: true },
      { id: 'no-recycle', name: '一周でクリア', desc: '山札を もう一周せずに クリアした', secret: true },
    ],
    icon: { emoji: '🃏', svg: ICON_SOLITAIRE },
    addedIn: '0.67.0',
    load: () => import('./solitaire/game'),
  },
  {
    id: 'sevens',
    no: 57,
    title: '七ならべ',
    kana: 'しちならべ',
    description: 'CPU2人と トランプの七ならべ。7から上下に カードをつなげて、手札を いちばん先に なくそう！パスは3回まで。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    // 順位で得点（1位150/2位80/3位20/脱落10）＝メダルは その値に合わせる（順位制の恒偽メダル回避）
    medals: { bronze: 20, silver: 80, gold: 150 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '7の となりから 順に（8,9…や 6,5…）カードを ならべて、手札を いちばん先に なくしたら 1位！',
      controls: [
        '出せるカード（黄色でひかる）を タップ：場に出す',
        '出せない/出したくないときは「パス」（3回まで・4回目で だつらく）',
        'CPU2人と じゅんばんに あそぶよ',
      ],
      tips: [
        '止めておきたい カードは パスで キープ（でも3回まで！）',
        'はしの カード（AやK）は 早めに 出すと あんしん',
        'だつらくすると 手札が ぜんぶ 場に出て みんなが 楽になるよ',
      ],
    },
    achievements: [
      { id: 'first-agari', name: 'はじめてのあがり', desc: 'はじめて 手札を なくした（あがり）' },
      { id: 'win', name: '1いになった', desc: '1位で あがった' },
      { id: 'top2', name: 'にゅうしょう', desc: '2位いないに なった' },
      { id: 'no-pass-win', name: 'ノーパスしょうり', desc: 'パス0回で 1位に なった', secret: true },
      { id: 'quick-win', name: 'そっこうあがり', desc: '8ターンいないで 1位に なった', secret: true },
      { id: 'win-3', name: '七ならべ名人', desc: 'あわせて3回 1位に なった', secret: true },
    ],
    icon: { emoji: '7️⃣' },
    addedIn: '0.67.0',
    load: () => import('./sevens/game'),
  },
  {
    id: 'up-jump',
    no: 58,
    title: 'うえうえジャンプ',
    kana: 'うえうえじゃんぷ',
    description: 'スマホを かたむけて 足場を ジャンプで のぼろう！バネで 大ジャンプ。落ちないように、どこまで 高く いけるかな？',
    category: 'sensor',
    orientation: 'portrait',
    optionalSensors: ['motion'],
    scoring: 'points',
    // スコア=のぼった高さ(m)。足場間隔は必ず1ジャンプで届く設計。理想ボットは700m超→人間ペース想定で較正・実機要調整
    medals: { bronze: 100, silver: 250, gold: 450 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: 'キャラは 自動で ジャンプするよ。足場に のりながら、できるだけ 高く のぼろう！下に 落ちたら おしまい。',
      controls: [
        'スマホを 左右に かたむける：キャラが 動く',
        '画面を 左右に ドラッグしてもOK（センサーがなくても あそべる）',
        '画面のはしから 反対がわへ ワープできる',
      ],
      tips: [
        'バネ（コイル）の 足場は 大ジャンプ！',
        '青い足場は 左右に 動くよ。タイミングを 見て',
        'かたむけすぎず、少しずつ 調整するのが コツ',
      ],
    },
    achievements: [
      { id: 'climb-50', name: 'はじめの50m', desc: '50m のぼった' },
      { id: 'climb-150', name: 'ぐんぐん150m', desc: '150m のぼった' },
      { id: 'climb-300', name: 'そらのうえ', desc: '300m のぼった', secret: true },
      { id: 'spring', name: 'ばよーん！', desc: 'バネで 大ジャンプした' },
      { id: 'moving', name: 'うごく足場マスター', desc: '動く足場に のった' },
      { id: 'score-hi', name: 'ジャンプめいじん', desc: '500m のぼった', secret: true },
    ],
    icon: { emoji: '🦘' },
    addedIn: '0.67.0',
    load: () => import('./up-jump/game'),
  },
  {
    id: 'road-cross',
    no: 59,
    title: 'ぴょんこのみちわたり',
    kana: 'ぴょんこのみちわたり',
    description: '車を よけ、丸太に 乗って、上の ゴールを めざす 定番わたりゲーム。何回 わたれるかな？ライフ3。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // ゴール到達+100・前進+5。E2Eの自動プレイで最大765点(5回わたり)→到達可能に較正・実機要調整
    medals: { bronze: 150, silver: 400, gold: 700 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '下から 上の 🏁ゴールまで わたろう！道路の 車に ぶつかる・川で 水に おちると ミス。ライフが3つ なくなったら おしまい。',
      controls: [
        'スワイプ（上下左右）：その向きに 1マス ジャンプ',
        '右下の 十字ボタンでもOK',
        '川では 丸太に のって わたる（水に おちないでね）',
      ],
      tips: [
        '車の すきまを 見て、あわてず 1マスずつ',
        '丸太は ながれる。はしから おちないように のりかえよう',
        'わたるほど スピードUP！ゴールごとに とくてん',
      ],
    },
    achievements: [
      { id: 'first-cross', name: 'はじめてのゴール', desc: 'はじめて 上まで わたった' },
      { id: 'cross-3', name: '3かいわたり', desc: '1プレイで 3回 わたった' },
      { id: 'cross-5', name: 'わたりの名人', desc: '1プレイで 5回 わたった', secret: true },
      { id: 'river-ride', name: 'まるのりマスター', desc: '丸太に のって 川を わたった' },
      { id: 'no-death-cross', name: 'ノーミスわたり', desc: '1回も ミスせずに わたった', secret: true },
      { id: 'score-hi', name: 'みちわたり王', desc: '800点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🐸' },
    addedIn: '0.67.0',
    load: () => import('./road-cross/game'),
  },
  {
    id: 'bowling',
    no: 60,
    title: 'ボウリング',
    kana: 'ぼうりんぐ',
    description: '下から上へ スワイプして ボールを投げ、10本のピンを たおそう！全10フレーム。ストライクや スペアで 高得点。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // 標準採点（パーフェクト300）。E2Eの自動投球で到達性を確認し較正・実機要調整
    medals: { bronze: 50, silver: 90, gold: 140 },
    timeToPlay: 'short',
    startMode: 'immediate',
    help: {
      goal: '10本の ピンを ボールで たおそう！2投で 1フレーム、ぜんぶで10フレームの 合計点で しょうぶ。',
      controls: [
        '画面を 下から上へ スワイプ：ボールを投げる',
        '横に ふって 投げると ねらいが かわる（カーブ）',
        '長く 強く スワイプすると 速く ころがる',
      ],
      tips: [
        '1投で ぜんぶ たおすと ストライク（大ボーナス）！',
        '2投で ぜんぶ たおすと スペア',
        'まん中より すこし ずらして 1番ピンの かたに 当てると たおれやすい',
      ],
    },
    achievements: [
      { id: 'first-strike', name: 'はつストライク', desc: 'ストライクを 出した' },
      { id: 'spare', name: 'スペアゲット', desc: 'スペアを 出した' },
      { id: 'strike-2', name: 'ストライク2かい', desc: '1ゲームで ストライクを2回 出した', secret: true },
      { id: 'turkey', name: 'ターキー！', desc: 'ストライクを 3回れんぞく 出した', secret: true },
      { id: 'score-80', name: 'スコア80', desc: '合計80点 いじょう とった' },
      { id: 'score-hi', name: 'ボウリング名人', desc: '合計150点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🎳' },
    addedIn: '0.67.0',
    load: () => import('./bowling/game'),
  },
  {
    id: 'pull-shot',
    no: 61,
    title: 'ひっぱりショット',
    kana: 'ひっぱりしょっと',
    description: '引っぱって はなして 発射！壁や岩で 反射させて、モンスターを まとめて たおそう。反撃される前に たおせるか？',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // ヒット20・たおすとHP×40・コンボ40×(n-1)・ステージクリア100+20×stage。
    // E2E狙撃ボット(直線のみ)の分布1240〜3540で較正: 金2500=ステージ4〜5到達級・実機要調整
    medals: { bronze: 500, silver: 1500, gold: 2500 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: 'ボールを 引っぱって はなすと 発射！モンスターに 当てて ぜんぶ たおすと ステージクリア。モンスターの数字が 0になると 反撃されて ライフ−1（3つで おしまい）。',
      controls: [
        '画面を ドラッグ：引っぱる（はなした 反対方向へ 飛ぶ）',
        '長く 引っぱるほど 速く 飛ぶ。壁や 岩で はねかえるよ',
        '1回の発射で 何体も 当てると コンボボーナス！',
      ],
      tips: [
        'モンスターの数字は「あと何回で 反撃」。0が near のこは 先に たおそう',
        '壁の はねかえりを つかうと 一直線に ならんだ敵を まとめて 撃てる',
        '👹は かたい、🦇は せっかち。ステージが すすむほど 手ごわい！',
      ],
    },
    achievements: [
      { id: 'first-kill', name: 'はじめてたおした', desc: 'モンスターを たおした' },
      { id: 'combo-3', name: 'トリプルヒット', desc: '1回の発射で 3体に 当てた' },
      { id: 'stage-3', name: 'ステージ3とうたつ', desc: 'ステージ3まで すすんだ' },
      { id: 'no-damage', name: 'ノーダメージ', desc: 'ひっかかれずに ステージを クリアした' },
      { id: 'stage-5', name: 'ダンジョンマスター', desc: 'ステージ5まで すすんだ', secret: true },
      { id: 'score-hi', name: 'ひっぱりの達人', desc: '1500点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🏹' },
    addedIn: '0.67.0',
    load: () => import('./pull-shot/game'),
  },
  {
    id: 'spot-diff',
    no: 62,
    title: 'まちがいさがし',
    kana: 'まちがいさがし',
    description: '上と下の絵を くらべて、ちがいを 5つ 見つけよう！絵は 毎回かわる。すり替え・鏡がえし・大きさ・回転・消える の5種類のまちがい。',
    category: 'chill',
    orientation: 'portrait',
    scoring: 'points',
    // 見つけた×40(=600)＋速さボーナス最大200/シーン＋ノーヒント40/シーン＝理論最大1320。
    // 完走だけで600＝銅は少しの速さで届く。金はテンポよく＋ノーヒント級。実機要調整
    medals: { bronze: 650, silver: 900, gold: 1150 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: '上（お手本）と 下（まちがい入り）の絵を くらべて、ちがう場所を 5つ タップで 見つけよう！ぜんぶで 3もん。',
      controls: [
        'ちがう場所を タップ（上の絵でも 下の絵でも OK）',
        'まちがえて タップすると 時間ペナルティ',
        '💡ヒント：1もんに 1回だけ、ちがいの場所を おしえてくれる',
      ],
      tips: [
        'まちがいは 5しゅるい：べつの絵・鏡がえし・大きさ・かたむき・消えている',
        'はしから じゅんばんに くらべると 見のがしにくい',
        'はやく ぜんぶ 見つけるほど ボーナスが 高い！',
      ],
    },
    achievements: [
      { id: 'first-find', name: 'はじめてのはっけん', desc: 'ちがいを はじめて 見つけた' },
      { id: 'scene-clear', name: '1もんコンプ', desc: '1もんぶんの ちがいを ぜんぶ 見つけた' },
      { id: 'all-clear', name: 'ぜんもんコンプ', desc: '3もん ぜんぶ 見つけきった' },
      { id: 'no-hint', name: 'じぶんの目で', desc: 'ヒントを つかわずに ぜんもんコンプ', secret: true },
      { id: 'sharp-eye', name: 'するどい目', desc: 'おてつき0で ぜんもんコンプ', secret: true },
      { id: 'score-hi', name: 'まちがいさがし名人', desc: '1000点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🔍' },
    addedIn: '0.67.0',
    load: () => import('./spot-diff/game'),
  },
  {
    id: 'ghost-tag',
    no: 63,
    title: 'かげぶんしんタッグ',
    kana: 'かげぶんしんたっぐ',
    description: '1回目のきみの うごきが「かげ」になって さいせい！2回目は かげと ふたりで きょうりょく。スイッチと とびらの タイミングパズル。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // 理論最大はE2Eの最適解ボットで実測（ほうせき9×30＋クリア3×100＋時間ボーナス）。実機要調整
    medals: { bronze: 350, silver: 600, gold: 780 },
    timeToPlay: 'mid',
    help: {
      goal: '1回目は「さくせん」: きみのうごきが かげに きろくされる。2回目は「ほんばん」: さいせいされる かげに とびらを あけてもらいながら、⭐ゴールをめざそう！',
      controls: [
        'スワイプ / 十字ボタン: 1マスうごく',
        'スイッチ床に のっている あいだだけ、同じ色の とびらが ひらく',
        '1回目: かげの「さくせん」をつくる（「かんりょう！」ボタンで おわる）',
        '2回目: かげが 1回目のとおりに うごく。きみは 下のキャラで ゴールへ！',
      ],
      tips: [
        'かげは さいごにいた ばしょに ずっと のこる。スイッチの上で「かんりょう！」が きほん',
        'とびらが 2つ以上ある ステージは、かげが スイッチにいる「時間」も だいじ',
        '💎ほうせきも わすれずに。とった数だけ 点数アップ！',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのタッグ', desc: 'はじめて ステージを クリアした' },
      { id: 'gems-stage', name: 'ぴかぴかコンビ', desc: '1つのステージの ほうせきを ぜんぶ あつめて クリアした' },
      { id: 'door-3', name: 'あうんのこきゅう', desc: 'かげが あけてくれた とびらを 1プレイで 3回 とおった' },
      { id: 'all-clear', name: 'さいこうのタッグ', desc: 'ステージ3まで ぜんぶ クリアした' },
      { id: 'fast-plan', name: 'さくせんめいじん', desc: 'さくせんを 12びょういないに きめて そのステージを クリアした', secret: true },
      { id: 'score-hi', name: 'タッグの達人', desc: '700点 いじょう とった', secret: true },
    ],
    icon: { emoji: '👥' },
    addedIn: '0.67.0',
    load: () => import('./ghost-tag/game'),
  },
  {
    id: 'sneak-ninja',
    no: 64,
    title: 'こっそりにんじゃ',
    kana: 'こっそりにんじゃ',
    description: '見張りの ひかりが 回る夜の庭。しげみから しげみへ タイミングよく ダッシュして、だんごを あつめつつ くらへ しのびこもう！',
    category: 'timing',
    orientation: 'portrait',
    scoring: 'points',
    // だんご12×20＋クリア3×100＋ノー発見3×50＋時間ボーナス。ボット実測で較正・実機要調整
    medals: { bronze: 400, silver: 650, gold: 820 },
    timeToPlay: 'mid',
    help: {
      goal: '見張りの「ひかりの扇」に 入らないように、しげみから しげみへ ダッシュ！🍡だんごを あつめながら、いちばん上の くらを めざそう。ぜんぶで3ステージ。',
      controls: [
        'いきたい しげみをタップ: ダッシュで うつる（線でつながった となりだけ）',
        'しげみの上は 安全。ダッシュ中に ひかりに 入ると 見つかる！',
        '3回 見つかると おしまい（とちゅうの点数は のこるよ）',
      ],
      tips: [
        'ひかりの 回りかたを よく見て、通りすぎた しゅんかんに ダッシュ！',
        '🍡を ぜんぶ あつめてから くらへ 行くと 点数アップ',
        'はやく クリアするほど 時間ボーナスが 大きい',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのおしのび', desc: 'はじめて ステージを クリアした' },
      { id: 'dango-stage', name: 'だんごコンプ', desc: '1つのステージの 🍡を ぜんぶ あつめた' },
      { id: 'no-found', name: 'かんぺきおしのび', desc: '1ステージを 一度も見つからずに クリアした' },
      { id: 'all-clear', name: 'くらにとうちゃく', desc: '3ステージ ぜんぶ クリアした' },
      { id: 'ghost-run', name: 'でんせつのにんじゃ', desc: '一度も見つからずに ぜんぶ クリアした', secret: true },
      { id: 'score-hi', name: 'にんじゃの達人', desc: '700点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🥷', svg: ICON_NINJA },
    addedIn: '0.67.0',
    load: () => import('./sneak-ninja/game'),
  },
  {
    id: 'spin-maze',
    no: 65,
    title: 'ぐるっとめいろ',
    kana: 'ぐるっとめいろ',
    description: '◀▶で めいろの世界ごと 90°回転！ボールが ころころ落ちる先を 先よみして、はた🚩まで みちびく 重力パズル。',
    category: 'puzzle',
    orientation: 'portrait',
    scoring: 'points',
    // 理論最大780（クリア100×3＋さいたんボーナス100×3＋ほうせき12×15）。E2E最適解ボットで到達実証・実機要調整
    medals: { bronze: 400, silver: 600, gold: 750 },
    timeToPlay: 'mid',
    startMode: 'immediate',
    help: {
      goal: '◀▶ボタンで めいろ全体を 90°ずつ 回すと、ボールが 下に ころがる。うまく ころがして、はた🚩の マスに とどけよう！ぜんぶで 3もん。',
      controls: [
        '◀ひだり / みぎ▶: 世界が 90°回って ボールが ころがる',
        'トゲ🔺に 入ると スタートから やりなおし（回した回数は そのまま）',
        '「やりなおす」: ボールを スタートに もどす（こまったとき用）',
      ],
      tips: [
        '回す前に「つぎは どこまで 落ちるかな？」を 先よみしよう',
        '「さいたん」の回数 ぴったりで とくと 大きなボーナス！',
        '💎ほうせきは さいたんルートの 上に あるよ',
      ],
    },
    achievements: [
      { id: 'first-clear', name: 'はじめてのかいてん', desc: 'はじめて もんだいを クリアした' },
      { id: 'par-just', name: 'さいたんぴったり', desc: 'さいたん回数 ぴったりで クリアした' },
      { id: 'gems-all', name: 'ほうせきハンター', desc: '1プレイで 💎を ぜんぶ あつめた' },
      { id: 'no-spike', name: 'トゲしらず', desc: 'トゲに 1回も あたらずに 3もん クリアした' },
      { id: 'all-par', name: 'かいてんマスター', desc: '3もん ぜんぶ さいたん回数で クリアした', secret: true },
      { id: 'score-hi', name: 'ぐるっとの達人', desc: '700点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🔄' },
    addedIn: '0.67.0',
    load: () => import('./spin-maze/game'),
  },
  {
    id: 'castle-guard',
    no: 66,
    title: 'まもれ！おしろ',
    kana: 'まもれおしろ',
    description: '道をあるいてくる敵から おしろをまもる はじめてのディフェンス！台に「まもりずきん」をたてて、強化して、全10ウェーブを むかえうとう。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // 撃破1203＋ウェーブ200＋城HP最大200＋クリア150＝理論最大1753。シム較正: けんじつ配置で1653・無防備はw1陥落。実機要調整
    medals: { bronze: 700, silver: 1200, gold: 1600 },
    timeToPlay: 'long',
    help: {
      goal: '道を あるいてくる敵を、道ぞいの台に たてた「まもりずきん」で むかえうとう！おしろに 5回 入られると まけ。全10ウェーブ まもりきれば かち！',
      controls: [
        'まるい台をタップ → 下のメニューから とりでを たてる（🪙コイン消費）',
        'とりでをタップ → 「つよくする」で レベルアップ（さいだいLv3）',
        '敵をたおすと 🪙コインが もらえる。ウェーブの間の 5びょうで じゅんびしよう',
      ],
      tips: [
        'ゆみ=はやい れんしゃ ／ こおり=敵を おそくする ／ ばくだん=まとめて ドカン',
        '道が おれまがる ところは、1つの とりでが ながく ねらえる とくとうせき！',
        'はやい敵👟には こおり、かたい敵には ばくだんが きく',
      ],
    },
    achievements: [
      { id: 'wave-5', name: 'がんばりウェーブ', desc: 'ウェーブ5まで すすんだ' },
      { id: 'builder-5', name: 'けんちくか', desc: '1プレイで とりでを 5つ たてた' },
      { id: 'max-up', name: 'さいきょうのとりで', desc: 'とりでを レベル3に した' },
      { id: 'clear-10', name: 'おしろをまもった', desc: '10ウェーブ ぜんぶ まもりきった' },
      { id: 'no-damage', name: 'むきずのおしろ', desc: 'おしろHP まんたんのまま クリアした', secret: true },
      { id: 'score-hi', name: 'でんせつのしゅび', desc: '1500点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🏰' },
    addedIn: '0.67.0',
    load: () => import('./castle-guard/game'),
  },
  {
    id: 'magnet-swing',
    no: 67,
    title: 'マグネットスイング',
    kana: 'まぐねっとすいんぐ',
    description: 'ながおしで 磁石にビームを つないで ぶらんぶらん→はなして ジャンプ！うみに おちないように どこまでも 右へ すすもう。',
    category: 'action',
    orientation: 'portrait',
    scoring: 'points',
    // きょり1m=1点＋⭐15点。到達可能性はソルバ実証（6シード×30アンカー≒250m）。実機要調整
    medals: { bronze: 120, silver: 280, gold: 500 },
    timeToPlay: 'short',
    help: {
      goal: 'ながおしで 🧲磁石に くっついて スイング、ゆびを はなすと そのいきおいで ジャンプ！つぎつぎ 磁石を のりついで、できるだけ 遠くへ とぼう。うみに おちたら おわり。',
      controls: [
        '画面を ながおし: いちばん近い 前の🧲に ビームが つながる（点線の わっかが 目じるし）',
        'おしている あいだ ブランコみたいに いきおいが つく',
        'ゆびを はなす: そのいきおいで ジャンプ！',
      ],
      tips: [
        '前ななめ上に むかって のぼる ときに はなすと 遠くへ とべる',
        '⭐は スイングの 下がわに ある。ひくく 通って あつめよう',
        'あわてず、つぎの🧲が 光ってから おしても まにあうよ',
      ],
    },
    achievements: [
      { id: 'first-fly', name: 'はじめてののりつぎ', desc: 'つぎの 磁石に のりついだ' },
      { id: 'dist-100', name: 'ぐんぐんスイング', desc: '100m とんだ' },
      { id: 'star-8', name: 'スターあつめ', desc: '1プレイで ⭐を 8こ とった' },
      { id: 'dist-250', name: 'おおぞらマスター', desc: '250m とんだ', secret: true },
      { id: 'big-fling', name: 'おおジャンプ', desc: '1回の ジャンプで おおきく とんだ', secret: true },
      { id: 'score-hi', name: 'スイングの達人', desc: '400点 いじょう とった', secret: true },
    ],
    icon: { emoji: '🧲' },
    addedIn: '0.67.0',
    load: () => import('./magnet-swing/game'),
  },
];

// 検証用ゲーム（開発ビルド限定。本番ビルドには一切含まれない）
if (import.meta.env.DEV) {
  const dev = await import('./dev/index');
  games.push(...dev.devGames);
}

/** 公開中のゲーム（retired を除き、番号順） */
export function activeGames(): GameMeta[] {
  return games.filter((g) => g.status !== 'retired').sort((a, b) => a.no - b.no);
}

export function gameById(id: string): GameMeta | undefined {
  return games.find((g) => g.id === id);
}
